spring.application.name=be-EE
spring.datasource.url=jdbc:postgresql://localhost:1434/KLTN
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.profiles.active=dev
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
JWT-SECRECT-KEY:h2KJ3wNxGqU5x6HsTjkF3pMdWbYd/D3as9NPl3T4GPM=

spring.security.oauth2.client.registration.google.client-id=732572235798-kd601sgkbei5mkh3rl1aecvf30943b0j.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile


spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

