--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.0

-- Started on 2025-06-02 23:33:25

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE "KLTN";
--
-- TOC entry 4930 (class 1262 OID 16387)
-- Name: KLTN; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "KLTN" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'English_United States.1252';


ALTER DATABASE "KLTN" OWNER TO postgres;

\connect "KLTN"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 4931 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- TOC entry 237 (class 1255 OID 16388)
-- Name: update_subscriber_number(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.update_subscriber_number() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    -- Khi có người subscribe (INSERT)
    IF TG_OP = 'INSERT' THEN
        UPDATE courses
        SET subscriber_number = subscriber_number + 1
        WHERE id = NEW.course_id;

    -- Khi có người unsubscribe (DELETE)
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE courses
        SET subscriber_number = subscriber_number - 1
        WHERE id = OLD.course_id;
    END IF;

    RETURN NULL;
END;
$$;


ALTER FUNCTION public.update_subscriber_number() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16389)
-- Name: accounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts (
    id character varying(255) NOT NULL,
    password character varying(255),
    provider character varying(255),
    role character varying(255) DEFAULT USER,
    is_locked boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.accounts OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16394)
-- Name: categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categories (
    id integer NOT NULL,
    name character varying(255),
    description character varying(255)
);


ALTER TABLE public.categories OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16399)
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16400)
-- Name: containers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.containers (
    id uuid NOT NULL,
    name character varying(255),
    created_at timestamp without time zone DEFAULT now(),
    course_id integer
);


ALTER TABLE public.containers OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16410)
-- Name: course_reviews; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.course_reviews (
    id integer NOT NULL,
    course_id integer,
    reviewer_id character varying(255),
    comment character varying(255),
    star_rate integer,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.course_reviews OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16416)
-- Name: course_review_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.course_reviews ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.course_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16417)
-- Name: courses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.courses (
    id integer NOT NULL,
    created_at timestamp(6) without time zone DEFAULT now(),
    creator_id character varying(255),
    description text,
    is_available boolean,
    price numeric(38,2),
    status character varying(255),
    thumbnail_url character varying(255),
    title character varying(255),
    category_id integer,
    subscriber_number bigint DEFAULT 0,
    is_featured boolean
);


ALTER TABLE public.courses OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16424)
-- Name: courses_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.courses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16425)
-- Name: files; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.files (
    id uuid NOT NULL,
    name character varying(255),
    type character varying(255),
    container_id uuid,
    created_at timestamp(6) without time zone DEFAULT now(),
    url text,
    extension character varying(255),
    author_id character varying(255),
    status character varying(255)
);


ALTER TABLE public.files OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 24579)
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications (
    id integer NOT NULL,
    created_at timestamp(6) without time zone DEFAULT now(),
    is_for_everyone boolean,
    message text,
    title character varying(255),
    receiver_id character varying(255),
    sender_id character varying(255)
);


ALTER TABLE public.notifications OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 24658)
-- Name: messages_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 57371)
-- Name: refund_requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.refund_requests (
    id integer NOT NULL,
    subscription_id integer,
    status character varying,
    user_reason character varying,
    created_at timestamp without time zone DEFAULT now(),
    update_at timestamp without time zone DEFAULT now(),
    admin_reason character varying
);


ALTER TABLE public.refund_requests OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 57370)
-- Name: refund_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.refund_requests ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.refund_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16431)
-- Name: subscriptions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.subscriptions (
    id integer NOT NULL,
    bought_price numeric(38,2),
    status character varying(255),
    created_at timestamp(6) without time zone DEFAULT now() NOT NULL,
    course_id integer,
    user_id character varying(255),
    is_available boolean DEFAULT true
);


ALTER TABLE public.subscriptions OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16437)
-- Name: subscription_records_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.subscriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscription_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 24601)
-- Name: user_favourites; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_favourites (
    id integer NOT NULL,
    created_at timestamp(6) without time zone DEFAULT now(),
    course_id integer,
    user_id character varying(255)
);


ALTER TABLE public.user_favourites OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 24600)
-- Name: user_favourites_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_favourites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_favourites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16438)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id character varying(255) NOT NULL,
    avatar_url character varying(255),
    email character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    phone character varying(255),
    is_male boolean DEFAULT true NOT NULL,
    birthdate date
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16443)
-- Name: vnpay_transaction_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vnpay_transaction_logs (
    bank_code character varying(255),
    created_at timestamp without time zone DEFAULT now(),
    user_id character varying(255),
    course_id integer,
    amount numeric(38,2),
    description character varying(255),
    is_successful boolean,
    payment_id character varying(255) NOT NULL,
    is_return_type boolean DEFAULT false,
    promote_amount numeric(38,2) DEFAULT 0,
    response_code smallint
);


ALTER TABLE public.vnpay_transaction_logs OWNER TO postgres;

--
-- TOC entry 4906 (class 0 OID 16389)
-- Dependencies: 218
-- Data for Name: accounts; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.accounts VALUES ('108654843953293656512', NULL, 'google', 'USER', false, NULL);
INSERT INTO public.accounts VALUES ('112941946199308652251', NULL, 'google', 'USER', false, NULL);
INSERT INTO public.accounts VALUES ('114137537600795110560', '$2a$10$bXTWv0SIwMDIyi4ncxgqfuTDRmFk9ryIC4meTHr.T7x9ZoHGweP7.', 'google', 'USER', false, NULL);
INSERT INTO public.accounts VALUES ('admin', '$2a$10$bXTWv0SIwMDIyi4ncxgqfuTDRmFk9ryIC4meTHr.T7x9ZoHGweP7.', 'google', 'ADMIN', false, NULL);
INSERT INTO public.accounts VALUES ('111392545229915064986', NULL, 'google', 'USER', NULL, NULL);
INSERT INTO public.accounts VALUES ('tkmoi123', '$2a$10$b12j5/i5MI0DeE4o6y85se55rB/4j.elYpm2sdoVDuUlfpxxfPHBe', 'default', 'USER', false, '2025-06-02 22:17:28.920322');


--
-- TOC entry 4907 (class 0 OID 16394)
-- Dependencies: 219
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.categories VALUES (5, 'Tiểu học / THCS', 'Bổ trợ kiến thức cấp Tiểu học và Trung học cơ sở');
INSERT INTO public.categories VALUES (6, 'Ngoại ngữ', 'Các khóa học tiếng Anh, Nhật, Hàn, TOEIC, IELTS,...');
INSERT INTO public.categories VALUES (7, 'Đời sống', 'Kiến thức đời sống như nuôi dạy con, tài chính cá nhân');
INSERT INTO public.categories VALUES (8, 'Kỹ năng mềm', 'Kỹ năng giao tiếp, làm việc nhóm, tư duy phản biện');
INSERT INTO public.categories VALUES (9, 'Tâm lý - Phát triển bản thân', 'EQ, kiểm soát cảm xúc, phát triển cá nhân');
INSERT INTO public.categories VALUES (10, 'Công nghệ thông tin', 'Tin học văn phòng, lập trình cơ bản');
INSERT INTO public.categories VALUES (11, 'Luyện thi chứng chỉ', 'MOS, IELTS, TOEIC, JLPT, các chứng chỉ chuyên môn');
INSERT INTO public.categories VALUES (12, 'Nghề nghiệp & Khởi nghiệp', 'Hướng nghiệp, viết CV, kỹ năng khởi nghiệp');
INSERT INTO public.categories VALUES (13, 'Kinh doanh & Marketing', 'Marketing online, bán hàng, quảng cáo');
INSERT INTO public.categories VALUES (14, 'Thiết kế & Sáng tạo', 'Thiết kế đồ họa, UI/UX, sáng tạo nội dung');
INSERT INTO public.categories VALUES (15, 'Pháp luật & Xã hội', 'Hiểu biết về luật pháp, xã hội và công dân');
INSERT INTO public.categories VALUES (16, 'Sức khỏe & Thể chất', 'Dinh dưỡng, yoga, thiền, rèn luyện thể chất');
INSERT INTO public.categories VALUES (1, 'Giáo dục', 'Kiến thức học thuật và kỹ năng học tập');
INSERT INTO public.categories VALUES (2, 'THPT', 'Ôn tập chương trình Trung học phổ thông');


--
-- TOC entry 4909 (class 0 OID 16400)
-- Dependencies: 221
-- Data for Name: containers; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.containers VALUES ('fa448942-18b9-451f-b15b-59a82fe5b633', 'gdgdfgdfg', '2025-05-11 00:25:08.968', 1);
INSERT INTO public.containers VALUES ('fa448942-18b9-451f-b15b-59a82fe5b639', 'gdgdfgdfg', '2025-05-11 00:25:08.968', 1);
INSERT INTO public.containers VALUES ('c5b3157b-81fd-4de2-a5a5-3f544bd71fa0', 'Các tài liệu quan trọng', '2025-05-11 20:49:54.131', 58);
INSERT INTO public.containers VALUES ('7a534c6e-9ca4-474e-8c6e-4207b27494e8', 'Nháp', '2025-05-15 04:33:03.252', 58);


--
-- TOC entry 4910 (class 0 OID 16410)
-- Dependencies: 222
-- Data for Name: course_reviews; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4912 (class 0 OID 16417)
-- Dependencies: 224
-- Data for Name: courses; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.courses VALUES (1, '2025-04-17 10:18:50.326729', 'admin', '<body id="tinymce" class="mce-content-body " data-id="tiny-react_45577982011746105294493" aria-label="Rich Text Area" contenteditable="true" spellcheck="false"><h1 style="text-align: center;" data-mce-style="text-align: center;"><span style="color: rgb(224, 62, 45);" data-mce-style="color: #e03e2d;">💻 🔥 Chinh Phục 9+ THPTQG Sinh Học 🔥 💻</span></h1><p>🎯 Ước mơ du học Y Dược đang chờ bạn? 🎯 Bạn băn khoăn về điểm chuẩn cao, không biết phải học như thế nào để đạt điểm số mơ ước? Đừng lo, khóa học "Chinh Phục 9+ THPTQG Sinh Học" chính là giải pháp tối ưu cho bạn! 💪</p><p>✅ Khóa học được thiết kế</p><ul><li>Với phương pháp giảng dạy khoa học, minh họa rõ ràng, dễ hiểu từ cơ bản đến nâng cao.</li><li>Mục tiêu giúp bạn đạt <strong>9 điểm trở lên thi THPTQG môn Sinh học.</strong></li><li>Tăng khả năng vận dụng kiến thức vào làm bài thi, chinh phục các dạng bài khó.</li></ul><p>✅ Với mức học phí chỉ 300k 💸, bạn đã có thể nắm trong tay khóa học chất lượng, giúp bạn</p><ul><li>Nâng cao kiến thức và kỹ năng thi môn Sinh học.</li><li>Rút ngắn thời gian ôn tập, tăng khả năng trúng nguyện Y Dược.</li><li>Tiết kiệm chi phí so với các khóa học khác.</li></ul><p>📚 Khóa học gồm:</p><ul><li>Các chương trình video học trực tuyến chất lượng cao.</li><li>Tài liệu học đầy đủ, dễ nắm bắt.</li><li>Bộ đề thi minh họa, đáp án chi tiết.</li><li>Hỗ trợ tư vấn 24/7 từ đội ngũ thầy cô giàu kinh nghiệm.</li></ul><p>💡 Hãy đăng ký ngay khóa học "Chinh Phục 9+ THPTQG Sinh Học" để:</p><ul><li>Tiến gần hơn đến ước mơ du học Y Dược.</li><li>Bắt đầu hành trình chinh phục 9 điểm Sinh học!</li></ul><p>🤷‍♂️ Thi THPT Quốc gia môn Sinh học thường bao gồm các nội dung sau:</p><ol><li>Kiến thức cơ bản về Sinh học lớp 12, bao gồm:</li></ol><ul><li>Di truyền học</li><li>Tiến hóa</li><li>Sinh thái học</li><li>Cơ thể sinh vật (cấu trúc và chức năng)</li></ul><ol start="2"><li>Các chủ đề trọng tâm:</li></ol><ul><li>Di truyền phân tử và di truyền tế bào</li><li>Cơ chế di truyền và biến dị</li><li>Ứng dụng di truyền học</li><li>Tiến hóa và đa dạng sinh học</li><li>Sinh thái và sinh quyển</li></ul><p>Môn thi Sinh học đánh giá khả năng hiểu và vận dụng kiến thức Sinh học của thí sinh. Câu hỏi có thể ở dạng lý thuyết hoặc bài tập thực hành.</p></body>', true, 150000.00, NULL, 'https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=1200&auto=format&fit=crop', 'Kỹ năng bán hàng đỉnh cao', 1, 0, true);
INSERT INTO public.courses VALUES (58, '2025-05-11 20:49:45.840319', 'admin', '<p>Explore the core mathematical knowledge of the 12th grade curriculum with our online course "12th Grade Math for High School Diploma". This course is specially designed to help you study effectively, efficiently, and achieve high scores in the High School Diploma exam.</p>
<p>The study plan for 12th-grade math exam preparation includes the following main topics:</p>
<ul>
<li>Functions: Investigating variations, graphing, solving, and discussing equations and inequalities of functions.</li>
<li>Limits, continuity, derivatives, and differentials: Applications in calculus and problems related to investigating functions.</li>
<li>Integrals: Methods of integration, applications of integrals in calculating areas, volumes, etc.</li>
<li>Exponential and logarithmic functions: Solving equations, inequalities, and applying logarithmic forms in mathematics.</li>
<li>Roots of equations: Discussing formulas for roots of high-degree equations.</li>
</ul>
<p>With engaging online teaching methods, combined with video solutions to example problems, practical exercises, and comprehensive study materials, you will master 12th-grade math knowledge and confidently enter the High School Diploma exam.</p>
<p>Alternatively, a more concise translation:</p>
<p>Discover the core math concepts of 12th grade with our online course. The course covers key topics:</p>
<ul>
<li>Functions</li>
<li>Limits, derivatives, and integrals</li>
<li>Exponential and logarithmic functions</li>
<li>Roots of equations</li>
</ul>
<p>With online lessons, example videos, practice exercises, and study materials, you''ll be well-prepared for the High School Diploma exam.</p>', true, 100000.00, NULL, 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1200&auto=format&fit=crop', 'Toán lớp 12 ôn thi THPT 1', 2, 2, true);


--
-- TOC entry 4914 (class 0 OID 16425)
-- Dependencies: 226
-- Data for Name: files; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.files VALUES ('ae95f65e-4d77-44e7-a615-7c6a962e2e22', 'fhfghfgh', 'iframe', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0', '2025-05-11 20:52:08.07', '<iframe width="560" height="315" src="https://www.youtube.com/embed/b_fbHSSp4Zk?si=DtNySdqo88srVYYJ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>', 'html', 'admin', NULL);
INSERT INTO public.files VALUES ('0c6ccd96-c01e-4b7c-a18e-85df8b62e9e8', 'mov', 'media-video', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0', '2025-05-11 22:05:03.636', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0/0c6ccd96-c01e-4b7c-a18e-85df8b62e9e8/0c6ccd96-c01e-4b7c-a18e-85df8b62e9e8.mov', 'mov', 'admin', NULL);
INSERT INTO public.files VALUES ('ab99ff32-24aa-4fb5-9a1a-6ffcf2b87579', 'fdgfdg', 'document', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0', '2025-05-11 22:13:45.58', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0/ab99ff32-24aa-4fb5-9a1a-6ffcf2b87579/ab99ff32-24aa-4fb5-9a1a-6ffcf2b87579.doc', 'doc', 'admin', NULL);
INSERT INTO public.files VALUES ('83f5fb7b-b081-41a9-8b23-928700b6bea2', 'hgfh', 'link', '7a534c6e-9ca4-474e-8c6e-4207b27494e8', '2025-05-15 04:33:09.519948', '123', 'url', 'admin', NULL);
INSERT INTO public.files VALUES ('b07622cf-4124-4d12-ba3c-f944d6534156', 'teestscorm', 'scorm', '7a534c6e-9ca4-474e-8c6e-4207b27494e8', '2025-05-16 23:11:09.291458', '7a534c6e-9ca4-474e-8c6e-4207b27494e8/b07622cf-4124-4d12-ba3c-f944d6534156/unzipped/HTML5_index.html', 'html', 'admin', NULL);
INSERT INTO public.files VALUES ('be9ba3fe-43dc-4765-8b3e-1eba46526126', 'hj,jlj', 'scorm', '7a534c6e-9ca4-474e-8c6e-4207b27494e8', '2025-05-19 08:47:06.130129', '7a534c6e-9ca4-474e-8c6e-4207b27494e8/be9ba3fe-43dc-4765-8b3e-1eba46526126/unzipped/HTML5_index.html', 'html', 'admin', NULL);
INSERT INTO public.files VALUES ('52855198-1aa1-4a86-9d4f-ff96f30ab554', '6', 'scorm', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0', '2025-05-11 22:14:21.516', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0/52855198-1aa1-4a86-9d4f-ff96f30ab554/unzipped/shared/launchpage.html', 'html', 'admin', NULL);
INSERT INTO public.files VALUES ('4b0fece0-ee59-4ea7-b257-7cdb80e7b878', '455', 'document', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0', '2025-05-11 20:51:18.955', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0/4b0fece0-ee59-4ea7-b257-7cdb80e7b878/4b0fece0-ee59-4ea7-b257-7cdb80e7b878.pptx', 'pptx', 'admin', NULL);
INSERT INTO public.files VALUES ('266858a4-6791-4f8b-add4-2d888efd36a6', 'nbmbnm', 'scorm', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0', '2025-05-22 17:34:26.858779', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0/266858a4-6791-4f8b-add4-2d888efd36a6/unzipped/shared/launchpage.html', 'html', 'admin', NULL);
INSERT INTO public.files VALUES ('7b4c3499-8a4e-43fa-8ade-b5d779e1dda5', 'Ảnh 1', 'media-image', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0', '2025-05-11 20:50:01.134', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0/7b4c3499-8a4e-43fa-8ade-b5d779e1dda5/7b4c3499-8a4e-43fa-8ade-b5d779e1dda5.png', 'png', 'admin', NULL);
INSERT INTO public.files VALUES ('74041759-dcbe-40b8-a90f-bece0a173ca3', 'Video 1', 'media-hls', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0', '2025-05-11 20:50:11.551', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0/74041759-dcbe-40b8-a90f-bece0a173ca3/hls/index.m3u8', 'm3u8', 'admin', NULL);
INSERT INTO public.files VALUES ('c61f644e-20a0-45c1-bafa-643f86762ffb', 'fdhdfgh', 'document', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0', '2025-05-11 20:51:55.984', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0/c61f644e-20a0-45c1-bafa-643f86762ffb/c61f644e-20a0-45c1-bafa-643f86762ffb.docx', 'docx', 'admin', NULL);
INSERT INTO public.files VALUES ('aa31672f-4747-4702-b2cc-1a5e6e48ac9b', 'k;kl;k', 'document', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0', '2025-05-11 21:06:34.996', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0/aa31672f-4747-4702-b2cc-1a5e6e48ac9b/aa31672f-4747-4702-b2cc-1a5e6e48ac9b.pdf', 'pdf', 'admin', NULL);
INSERT INTO public.files VALUES ('2468b1be-21e3-4233-8a74-6f12306bdc8a', 'ghfhgfgh', 'link', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0', '2025-05-11 20:52:04.614', 'https://www.google.com', 'url', 'admin', NULL);
INSERT INTO public.files VALUES ('2c5503ee-0781-48d5-b27c-ddb99fb75514', 'File âm thanh', 'media-audio', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0', '2025-05-11 20:50:54.948', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0/2c5503ee-0781-48d5-b27c-ddb99fb75514/2c5503ee-0781-48d5-b27c-ddb99fb75514.mp3', 'mp3', 'admin', NULL);
INSERT INTO public.files VALUES ('86ead9f5-3564-4d4b-af9f-31c836cf7416', 'File SCORM ', 'scorm', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0', '2025-05-11 20:51:11.295', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0/86ead9f5-3564-4d4b-af9f-31c836cf7416/unzipped/res/index.html', 'html', 'admin', NULL);


--
-- TOC entry 4919 (class 0 OID 24579)
-- Dependencies: 231
-- Data for Name: notifications; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.notifications VALUES (134, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (135, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (136, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (137, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (138, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (139, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (140, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (141, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (142, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (143, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (144, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (145, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (146, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (147, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (148, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (149, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (150, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (151, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (152, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (155, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (154, '2025-05-18 12:18:54.648', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (156, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (157, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (158, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (159, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (160, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (161, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (162, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (163, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (164, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (165, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (166, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (167, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (168, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (169, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (170, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (171, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (172, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (173, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (174, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (175, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (176, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (177, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (178, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (179, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (180, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (181, '2025-05-18 11:18:54.648589', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');
INSERT INTO public.notifications VALUES (153, '2025-05-18 20:05:01.599742', true, '<h2>Why do we use it?</h2>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', 'Push Notification Preview Tool', NULL, 'admin');


--
-- TOC entry 4924 (class 0 OID 57371)
-- Dependencies: 236
-- Data for Name: refund_requests; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4915 (class 0 OID 16431)
-- Dependencies: 227
-- Data for Name: subscriptions; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.subscriptions VALUES (13, 10000.00, NULL, '2025-05-16 04:43:19.771839', 58, '112941946199308652251', true);
INSERT INTO public.subscriptions VALUES (14, 100000.00, NULL, '2025-05-19 12:59:23.725884', 58, '114137537600795110560', true);


--
-- TOC entry 4921 (class 0 OID 24601)
-- Dependencies: 233
-- Data for Name: user_favourites; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.user_favourites VALUES (29, '2025-05-18 05:29:37.916249', 1, 'admin');
INSERT INTO public.user_favourites VALUES (32, '2025-05-18 05:41:48.831026', 58, 'admin');


--
-- TOC entry 4917 (class 0 OID 16438)
-- Dependencies: 229
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.users VALUES ('114137537600795110560', 'https://pub-e96712ffb5c644eab6d6682c1ebe8bf3.r2.dev/avatars/f33fa4b6-0526-437f-830d-3d210837e88d', 'ducle14050301@gmail.com', 'Duc', 'Minh', NULL, true, NULL);
INSERT INTO public.users VALUES ('108654843953293656512', 'https://pub-e96712ffb5c644eab6d6682c1ebe8bf3.r2.dev/avatars/0ad613e7-30e9-44f8-9ce9-3615453cae88', 'leduc14503@gmail.com', 'Đức', 'Lê', NULL, true, NULL);
INSERT INTO public.users VALUES ('112941946199308652251', 'https://pub-e96712ffb5c644eab6d6682c1ebe8bf3.r2.dev/avatars/47b447dd-4ef4-4a1e-813f-bc76d32a55aa', '21t1080009@husc.edu.vn', 'Đức', 'Lê Minh', NULL, true, NULL);
INSERT INTO public.users VALUES ('admin', 'https://pub-e96712ffb5c644eab6d6682c1ebe8bf3.r2.dev/avatars/0cb83687-537f-446f-9e8f-462c1ed71f5c', 'ducle140503@gmail.com', 'Đức', 'Minh', '0123456789', true, NULL);
INSERT INTO public.users VALUES ('111392545229915064986', 'https://pub-e96712ffb5c644eab6d6682c1ebe8bf3.r2.dev/avatars/e1e136b6-257f-4251-be1d-121b5a36b7bc', 'ducle14050304@gmail.com', 'Duc', 'Minh', NULL, true, NULL);
INSERT INTO public.users VALUES ('tkmoi123', NULL, 'tkmoi123@email.com', 'Tài khoản', 'Mới', '0123456788', false, '2020-03-01');


--
-- TOC entry 4918 (class 0 OID 16443)
-- Dependencies: 230
-- Data for Name: vnpay_transaction_logs; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4932 (class 0 OID 0)
-- Dependencies: 220
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categories_id_seq', 23, true);


--
-- TOC entry 4933 (class 0 OID 0)
-- Dependencies: 223
-- Name: course_review_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.course_review_id_seq', 191, true);


--
-- TOC entry 4934 (class 0 OID 0)
-- Dependencies: 225
-- Name: courses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.courses_id_seq', 177, true);


--
-- TOC entry 4935 (class 0 OID 0)
-- Dependencies: 234
-- Name: messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.messages_id_seq', 181, true);


--
-- TOC entry 4936 (class 0 OID 0)
-- Dependencies: 235
-- Name: refund_requests_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.refund_requests_id_seq', 1, false);


--
-- TOC entry 4937 (class 0 OID 0)
-- Dependencies: 228
-- Name: subscription_records_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.subscription_records_id_seq', 14, true);


--
-- TOC entry 4938 (class 0 OID 0)
-- Dependencies: 232
-- Name: user_favourites_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_favourites_id_seq', 32, true);


--
-- TOC entry 4718 (class 2606 OID 16451)
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);


--
-- TOC entry 4720 (class 2606 OID 16453)
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- TOC entry 4728 (class 2606 OID 16457)
-- Name: files course_file_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.files
    ADD CONSTRAINT course_file_pk PRIMARY KEY (id);


--
-- TOC entry 4722 (class 2606 OID 16459)
-- Name: containers course_folder_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.containers
    ADD CONSTRAINT course_folder_pk PRIMARY KEY (id);


--
-- TOC entry 4724 (class 2606 OID 16461)
-- Name: course_reviews course_review_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_reviews
    ADD CONSTRAINT course_review_pk PRIMARY KEY (id);


--
-- TOC entry 4726 (class 2606 OID 16463)
-- Name: courses courses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT courses_pkey PRIMARY KEY (id);


--
-- TOC entry 4738 (class 2606 OID 40982)
-- Name: notifications messages_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT messages_pk PRIMARY KEY (id);


--
-- TOC entry 4742 (class 2606 OID 57375)
-- Name: refund_requests refund_requests_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refund_requests
    ADD CONSTRAINT refund_requests_pk PRIMARY KEY (id);


--
-- TOC entry 4730 (class 2606 OID 16465)
-- Name: subscriptions subscription_records_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscription_records_pkey PRIMARY KEY (id);


--
-- TOC entry 4740 (class 2606 OID 24605)
-- Name: user_favourites user_favourites_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_favourites
    ADD CONSTRAINT user_favourites_pkey PRIMARY KEY (id);


--
-- TOC entry 4732 (class 2606 OID 16467)
-- Name: users users_email_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_unique UNIQUE (email);


--
-- TOC entry 4734 (class 2606 OID 16469)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4736 (class 2606 OID 57413)
-- Name: vnpay_transaction_logs vnpay_transaction_logs_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vnpay_transaction_logs
    ADD CONSTRAINT vnpay_transaction_logs_pk PRIMARY KEY (payment_id);


--
-- TOC entry 4760 (class 2620 OID 16472)
-- Name: subscriptions trg_update_subscriber_number; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_update_subscriber_number AFTER INSERT OR DELETE ON public.subscriptions FOR EACH ROW EXECUTE FUNCTION public.update_subscriber_number();


--
-- TOC entry 4749 (class 2606 OID 16483)
-- Name: files course_file_course_folder_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.files
    ADD CONSTRAINT course_file_course_folder_fk FOREIGN KEY (container_id) REFERENCES public.containers(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4745 (class 2606 OID 16488)
-- Name: course_reviews course_review_courses_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_reviews
    ADD CONSTRAINT course_review_courses_fk FOREIGN KEY (course_id) REFERENCES public.courses(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4746 (class 2606 OID 24647)
-- Name: course_reviews course_review_users_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_reviews
    ADD CONSTRAINT course_review_users_fk FOREIGN KEY (reviewer_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4747 (class 2606 OID 49173)
-- Name: courses fk41jwvqd779kdvc0rdgij4ct17; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT fk41jwvqd779kdvc0rdgij4ct17 FOREIGN KEY (creator_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 4755 (class 2606 OID 24680)
-- Name: notifications fk4ui4nnwntodh6wjvck53dbk9m; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk4ui4nnwntodh6wjvck53dbk9m FOREIGN KEY (sender_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4748 (class 2606 OID 24690)
-- Name: courses fk72l5dj585nq7i6xxv1vj51lyn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT fk72l5dj585nq7i6xxv1vj51lyn FOREIGN KEY (category_id) REFERENCES public.categories(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 4757 (class 2606 OID 24617)
-- Name: user_favourites fkf4mgriav7n8cijq18001fsy6e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_favourites
    ADD CONSTRAINT fkf4mgriav7n8cijq18001fsy6e FOREIGN KEY (course_id) REFERENCES public.courses(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4751 (class 2606 OID 16513)
-- Name: subscriptions fkfhysei663mq62wa646n5mv5k1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT fkfhysei663mq62wa646n5mv5k1 FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4750 (class 2606 OID 24592)
-- Name: files fkj1y8cv1ty40nltgt267oqwmk8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.files
    ADD CONSTRAINT fkj1y8cv1ty40nltgt267oqwmk8 FOREIGN KEY (author_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4743 (class 2606 OID 16518)
-- Name: accounts fklsevhk46j1mfa8r9bak4tr4x3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT fklsevhk46j1mfa8r9bak4tr4x3 FOREIGN KEY (id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4752 (class 2606 OID 16523)
-- Name: subscriptions fkm5q12n9cpt2e99beegi4so04t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT fkm5q12n9cpt2e99beegi4so04t FOREIGN KEY (course_id) REFERENCES public.courses(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4758 (class 2606 OID 24622)
-- Name: user_favourites fksotykjapinh9k0qddenalw94k; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_favourites
    ADD CONSTRAINT fksotykjapinh9k0qddenalw94k FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4756 (class 2606 OID 24675)
-- Name: notifications fkt05r0b6n0iis8u7dfna4xdh73; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fkt05r0b6n0iis8u7dfna4xdh73 FOREIGN KEY (receiver_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4744 (class 2606 OID 24587)
-- Name: containers fkt2s02o8n8cpl64ctd5q5fkyp3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.containers
    ADD CONSTRAINT fkt2s02o8n8cpl64ctd5q5fkyp3 FOREIGN KEY (course_id) REFERENCES public.courses(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4759 (class 2606 OID 57376)
-- Name: refund_requests refund_requests_subscriptions_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refund_requests
    ADD CONSTRAINT refund_requests_subscriptions_fk FOREIGN KEY (id) REFERENCES public.subscriptions(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4753 (class 2606 OID 16533)
-- Name: vnpay_transaction_logs vnpay_transaction_logs_courses_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vnpay_transaction_logs
    ADD CONSTRAINT vnpay_transaction_logs_courses_fk FOREIGN KEY (course_id) REFERENCES public.courses(id) ON UPDATE CASCADE;


--
-- TOC entry 4754 (class 2606 OID 57426)
-- Name: vnpay_transaction_logs vnpay_transaction_logs_users_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vnpay_transaction_logs
    ADD CONSTRAINT vnpay_transaction_logs_users_fk FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE;


-- Completed on 2025-06-02 23:33:25

--
-- PostgreSQL database dump complete
--

