--
-- PostgreSQL database cluster dump
--

-- Started on 2025-04-15 22:19:16

SET default_transaction_read_only = off;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

--
-- Roles
--

CREATE ROLE postgres;
ALTER ROLE postgres WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION BYPASSRLS;

--
-- User Configurations
--








--
-- Databases
--

--
-- Database "template1" dump
--

\connect template1

--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.0

-- Started on 2025-04-15 22:19:16

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- Completed on 2025-04-15 22:19:17

--
-- PostgreSQL database dump complete
--

--
-- Database "KLTN" dump
--

--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.0

-- Started on 2025-04-15 22:19:17

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4876 (class 1262 OID 16387)
-- Name: KLTN; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "KLTN" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Vietnamese_Vietnam.1258';


ALTER DATABASE "KLTN" OWNER TO postgres;

\connect "KLTN"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 2 (class 3079 OID 16514)
-- Name: unaccent; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA public;


--
-- TOC entry 4877 (class 0 OID 0)
-- Dependencies: 2
-- Name: EXTENSION unaccent; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION unaccent IS 'text search dictionary that removes accents';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16388)
-- Name: accounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts (
    id character varying(255) NOT NULL,
    password character varying(255),
    provider character varying(255),
    role character varying(255)
);


ALTER TABLE public.accounts OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16396)
-- Name: categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categories (
    id integer NOT NULL,
    name character varying(255)
);


ALTER TABLE public.categories OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16395)
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16459)
-- Name: container; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.container (
    id integer NOT NULL
);


ALTER TABLE public.container OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16462)
-- Name: container_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.container ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.container_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16487)
-- Name: course_file; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.course_file (
    id uuid NOT NULL,
    name character varying,
    create_at timestamp without time zone,
    type character varying(3),
    folder_id uuid
);


ALTER TABLE public.course_file OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16475)
-- Name: course_folder; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.course_folder (
    id uuid NOT NULL,
    name character varying(255),
    container_id integer,
    created_at timestamp without time zone
);


ALTER TABLE public.course_folder OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 16522)
-- Name: course_review; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.course_review (
    id integer NOT NULL,
    course_id integer,
    reviewer_id character varying,
    comment text,
    star_rate smallint,
    created_at timestamp without time zone
);


ALTER TABLE public.course_review OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16521)
-- Name: course_review_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.course_review ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.course_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16402)
-- Name: courses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.courses (
    id integer NOT NULL,
    created_at date,
    creator_id character varying(255),
    description text,
    is_available boolean,
    price numeric(38,2),
    status character varying(255),
    thumbnail_url character varying(255),
    title character varying(255),
    category_id integer,
    container_id integer
);


ALTER TABLE public.courses OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16401)
-- Name: courses_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.courses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16410)
-- Name: subscription; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.subscription (
    id integer NOT NULL,
    bought_price numeric(38,2),
    status character varying(255),
    subscribed_at timestamp(6) without time zone,
    course_id integer,
    user_id character varying(255)
);


ALTER TABLE public.subscription OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16409)
-- Name: subscription_records_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.subscription ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscription_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16417)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id character varying(255) NOT NULL,
    avatar_url character varying(255),
    email character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    container_id integer
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 4857 (class 0 OID 16388)
-- Dependencies: 218
-- Data for Name: accounts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts (id, password, provider, role) FROM stdin;
admin	$2a$10$o6lICJPWxVbhFVTzJ6G1puqNtGuvmEeaJPjESma7J5MUSTm1yNpha	google	ADMIN
\.


--
-- TOC entry 4859 (class 0 OID 16396)
-- Dependencies: 220
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.categories (id, name) FROM stdin;
1	Loại 1
\.


--
-- TOC entry 4865 (class 0 OID 16459)
-- Dependencies: 226
-- Data for Name: container; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.container (id) FROM stdin;
\.


--
-- TOC entry 4868 (class 0 OID 16487)
-- Dependencies: 229
-- Data for Name: course_file; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.course_file (id, name, create_at, type, folder_id) FROM stdin;
\.


--
-- TOC entry 4867 (class 0 OID 16475)
-- Dependencies: 228
-- Data for Name: course_folder; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.course_folder (id, name, container_id, created_at) FROM stdin;
\.


--
-- TOC entry 4870 (class 0 OID 16522)
-- Dependencies: 231
-- Data for Name: course_review; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.course_review (id, course_id, reviewer_id, comment, star_rate, created_at) FROM stdin;
\.


--
-- TOC entry 4861 (class 0 OID 16402)
-- Dependencies: 222
-- Data for Name: courses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.courses (id, created_at, creator_id, description, is_available, price, status, thumbnail_url, title, category_id, container_id) FROM stdin;
\.


--
-- TOC entry 4863 (class 0 OID 16410)
-- Dependencies: 224
-- Data for Name: subscription; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.subscription (id, bought_price, status, subscribed_at, course_id, user_id) FROM stdin;
\.


--
-- TOC entry 4864 (class 0 OID 16417)
-- Dependencies: 225
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, avatar_url, email, first_name, last_name, container_id) FROM stdin;
admin	https://lh3.googleusercontent.com/a/ACg8ocLzGeafaRFo6EX1ckIUjB5DjW9FEI3wx2ol7_s2kWAFFnftgXCy=s96-c	ducle140503@gmail.com	Đức	Minh	\N
\.


--
-- TOC entry 4878 (class 0 OID 0)
-- Dependencies: 219
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categories_id_seq', 1, true);


--
-- TOC entry 4879 (class 0 OID 0)
-- Dependencies: 227
-- Name: container_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.container_id_seq', 1, false);


--
-- TOC entry 4880 (class 0 OID 0)
-- Dependencies: 230
-- Name: course_review_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.course_review_id_seq', 1, false);


--
-- TOC entry 4881 (class 0 OID 0)
-- Dependencies: 221
-- Name: courses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.courses_id_seq', 1, false);


--
-- TOC entry 4882 (class 0 OID 0)
-- Dependencies: 223
-- Name: subscription_records_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.subscription_records_id_seq', 1, false);


--
-- TOC entry 4685 (class 2606 OID 16394)
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);


--
-- TOC entry 4687 (class 2606 OID 16400)
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- TOC entry 4695 (class 2606 OID 16467)
-- Name: container container_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.container
    ADD CONSTRAINT container_pk PRIMARY KEY (id);


--
-- TOC entry 4699 (class 2606 OID 16491)
-- Name: course_file course_file_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_file
    ADD CONSTRAINT course_file_pk PRIMARY KEY (id);


--
-- TOC entry 4697 (class 2606 OID 16479)
-- Name: course_folder course_folder_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_folder
    ADD CONSTRAINT course_folder_pk PRIMARY KEY (id);


--
-- TOC entry 4701 (class 2606 OID 16528)
-- Name: course_review course_review_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_review
    ADD CONSTRAINT course_review_pk PRIMARY KEY (id);


--
-- TOC entry 4689 (class 2606 OID 16408)
-- Name: courses courses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT courses_pkey PRIMARY KEY (id);


--
-- TOC entry 4691 (class 2606 OID 16416)
-- Name: subscription subscription_records_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscription
    ADD CONSTRAINT subscription_records_pkey PRIMARY KEY (id);


--
-- TOC entry 4693 (class 2606 OID 16423)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4709 (class 2606 OID 16494)
-- Name: course_file course_file_course_folder_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_file
    ADD CONSTRAINT course_file_course_folder_fk FOREIGN KEY (folder_id) REFERENCES public.course_folder(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4708 (class 2606 OID 16482)
-- Name: course_folder course_folder_container_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_folder
    ADD CONSTRAINT course_folder_container_fk FOREIGN KEY (container_id) REFERENCES public.container(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4710 (class 2606 OID 16534)
-- Name: course_review course_review_courses_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_review
    ADD CONSTRAINT course_review_courses_fk FOREIGN KEY (course_id) REFERENCES public.courses(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4711 (class 2606 OID 16529)
-- Name: course_review course_review_users_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_review
    ADD CONSTRAINT course_review_users_fk FOREIGN KEY (reviewer_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4703 (class 2606 OID 16434)
-- Name: courses fk41jwvqd779kdvc0rdgij4ct17; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT fk41jwvqd779kdvc0rdgij4ct17 FOREIGN KEY (creator_id) REFERENCES public.users(id);


--
-- TOC entry 4704 (class 2606 OID 16429)
-- Name: courses fk72l5dj585nq7i6xxv1vj51lyn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT fk72l5dj585nq7i6xxv1vj51lyn FOREIGN KEY (category_id) REFERENCES public.categories(id);


--
-- TOC entry 4705 (class 2606 OID 16546)
-- Name: subscription fkfhysei663mq62wa646n5mv5k1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscription
    ADD CONSTRAINT fkfhysei663mq62wa646n5mv5k1 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 4702 (class 2606 OID 16449)
-- Name: accounts fklsevhk46j1mfa8r9bak4tr4x3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT fklsevhk46j1mfa8r9bak4tr4x3 FOREIGN KEY (id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4706 (class 2606 OID 16439)
-- Name: subscription fkm5q12n9cpt2e99beegi4so04t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscription
    ADD CONSTRAINT fkm5q12n9cpt2e99beegi4so04t FOREIGN KEY (course_id) REFERENCES public.courses(id);


--
-- TOC entry 4707 (class 2606 OID 16499)
-- Name: users users_container_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_container_fk FOREIGN KEY (container_id) REFERENCES public.container(id);


-- Completed on 2025-04-15 22:19:18

--
-- PostgreSQL database dump complete
--

--
-- Database "postgres" dump
--

\connect postgres

--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.0

-- Started on 2025-04-15 22:19:18

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- Completed on 2025-04-15 22:19:18

--
-- PostgreSQL database dump complete
--

-- Completed on 2025-04-15 22:19:18

--
-- PostgreSQL database cluster dump complete
--

