--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.0

-- Started on 2025-04-16 11:21:04

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4907 (class 1262 OID 16387)
-- Name: KLTN; Type: DATABASE; Schema: -; Owner: -
--

CREATE DATABASE "KLTN" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Vietnamese_Vietnam.1258';


\connect "KLTN"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- TOC entry 4908 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16388)
-- Name: accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts (
    id character varying(255) NOT NULL,
    password character varying(255),
    provider character varying(255),
    role character varying(255)
);


--
-- TOC entry 220 (class 1259 OID 16396)
-- Name: categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categories (
    id integer NOT NULL,
    name character varying(255),
    description character varying
);


--
-- TOC entry 219 (class 1259 OID 16395)
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16459)
-- Name: containers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.containers (
    id integer NOT NULL,
    owner_id character varying
);


--
-- TOC entry 227 (class 1259 OID 16462)
-- Name: container_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.containers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.container_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 16606)
-- Name: course_data; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_data (
    id integer NOT NULL,
    folder_id uuid,
    course_id integer
);


--
-- TOC entry 234 (class 1259 OID 16605)
-- Name: course_data_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.course_data ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.course_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 16522)
-- Name: course_reviews; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_reviews (
    id integer NOT NULL,
    course_id integer,
    reviewer_id character varying,
    comment text,
    star_rate smallint,
    created_at timestamp without time zone DEFAULT now()
);


--
-- TOC entry 230 (class 1259 OID 16521)
-- Name: course_review_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.course_reviews ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.course_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16402)
-- Name: courses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.courses (
    id integer NOT NULL,
    created_at date DEFAULT now(),
    creator_id character varying(255),
    description text,
    is_available boolean,
    price numeric(38,2),
    status character varying(255),
    thumbnail_url character varying(255),
    title character varying(255),
    category_id integer
);


--
-- TOC entry 221 (class 1259 OID 16401)
-- Name: courses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.courses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16487)
-- Name: files; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.files (
    id uuid NOT NULL,
    name character varying,
    create_at timestamp without time zone DEFAULT now(),
    type character varying(5),
    folder_id uuid
);


--
-- TOC entry 228 (class 1259 OID 16475)
-- Name: folders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.folders (
    id uuid NOT NULL,
    name character varying(255),
    container_id integer,
    created_at timestamp without time zone DEFAULT now()
);


--
-- TOC entry 224 (class 1259 OID 16410)
-- Name: subscriptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subscriptions (
    id integer NOT NULL,
    bought_price numeric(38,2),
    status character varying(255),
    created_at timestamp(6) without time zone DEFAULT now(),
    course_id integer,
    user_id character varying(255)
);


--
-- TOC entry 223 (class 1259 OID 16409)
-- Name: subscription_records_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.subscriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscription_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16417)
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id character varying(255) NOT NULL,
    avatar_url character varying(255),
    email character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    phone character varying(10)
);


--
-- TOC entry 233 (class 1259 OID 16571)
-- Name: vnpay_transaction_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vnpay_transaction_logs (
    id integer NOT NULL,
    order_id character varying(255),
    amount bigint,
    bank_code character varying(20),
    transaction_status character varying(10),
    response_code character varying(10),
    pay_date timestamp without time zone,
    secure_hash text,
    created_at timestamp without time zone DEFAULT now(),
    user_id character varying,
    course_id integer
);


--
-- TOC entry 232 (class 1259 OID 16570)
-- Name: vnpay_transaction_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.vnpay_transaction_logs_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 4909 (class 0 OID 0)
-- Dependencies: 232
-- Name: vnpay_transaction_logs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.vnpay_transaction_logs_id_seq OWNED BY public.vnpay_transaction_logs.id;


--
-- TOC entry 4699 (class 2604 OID 16585)
-- Name: vnpay_transaction_logs id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vnpay_transaction_logs ALTER COLUMN id SET DEFAULT nextval('public.vnpay_transaction_logs_id_seq'::regclass);


--
-- TOC entry 4884 (class 0 OID 16388)
-- Dependencies: 218
-- Data for Name: accounts; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.accounts VALUES ('admin', '$2a$10$o6lICJPWxVbhFVTzJ6G1puqNtGuvmEeaJPjESma7J5MUSTm1yNpha', 'google', 'ADMIN');


--
-- TOC entry 4886 (class 0 OID 16396)
-- Dependencies: 220
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.categories VALUES (1, 'Loại 1', NULL);


--
-- TOC entry 4892 (class 0 OID 16459)
-- Dependencies: 226
-- Data for Name: containers; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4901 (class 0 OID 16606)
-- Dependencies: 235
-- Data for Name: course_data; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4897 (class 0 OID 16522)
-- Dependencies: 231
-- Data for Name: course_reviews; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4888 (class 0 OID 16402)
-- Dependencies: 222
-- Data for Name: courses; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4895 (class 0 OID 16487)
-- Dependencies: 229
-- Data for Name: files; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4894 (class 0 OID 16475)
-- Dependencies: 228
-- Data for Name: folders; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4890 (class 0 OID 16410)
-- Dependencies: 224
-- Data for Name: subscriptions; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4891 (class 0 OID 16417)
-- Dependencies: 225
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.users VALUES ('admin', 'https://lh3.googleusercontent.com/a/ACg8ocLzGeafaRFo6EX1ckIUjB5DjW9FEI3wx2ol7_s2kWAFFnftgXCy=s96-c', 'ducle140503@gmail.com', 'Đức', 'Minh', '0123456789');


--
-- TOC entry 4899 (class 0 OID 16571)
-- Dependencies: 233
-- Data for Name: vnpay_transaction_logs; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4910 (class 0 OID 0)
-- Dependencies: 219
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.categories_id_seq', 1, true);


--
-- TOC entry 4911 (class 0 OID 0)
-- Dependencies: 227
-- Name: container_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.container_id_seq', 1, false);


--
-- TOC entry 4912 (class 0 OID 0)
-- Dependencies: 234
-- Name: course_data_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.course_data_id_seq', 1, false);


--
-- TOC entry 4913 (class 0 OID 0)
-- Dependencies: 230
-- Name: course_review_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.course_review_id_seq', 1, false);


--
-- TOC entry 4914 (class 0 OID 0)
-- Dependencies: 221
-- Name: courses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.courses_id_seq', 1, false);


--
-- TOC entry 4915 (class 0 OID 0)
-- Dependencies: 223
-- Name: subscription_records_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.subscription_records_id_seq', 1, false);


--
-- TOC entry 4916 (class 0 OID 0)
-- Dependencies: 232
-- Name: vnpay_transaction_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.vnpay_transaction_logs_id_seq', 1, false);


--
-- TOC entry 4702 (class 2606 OID 16394)
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);


--
-- TOC entry 4704 (class 2606 OID 16400)
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- TOC entry 4714 (class 2606 OID 16467)
-- Name: containers container_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.containers
    ADD CONSTRAINT container_pk PRIMARY KEY (id);


--
-- TOC entry 4724 (class 2606 OID 16610)
-- Name: course_data course_data_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_data
    ADD CONSTRAINT course_data_pk PRIMARY KEY (id);


--
-- TOC entry 4718 (class 2606 OID 16491)
-- Name: files course_file_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.files
    ADD CONSTRAINT course_file_pk PRIMARY KEY (id);


--
-- TOC entry 4716 (class 2606 OID 16479)
-- Name: folders course_folder_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.folders
    ADD CONSTRAINT course_folder_pk PRIMARY KEY (id);


--
-- TOC entry 4720 (class 2606 OID 16528)
-- Name: course_reviews course_review_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_reviews
    ADD CONSTRAINT course_review_pk PRIMARY KEY (id);


--
-- TOC entry 4706 (class 2606 OID 16408)
-- Name: courses courses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT courses_pkey PRIMARY KEY (id);


--
-- TOC entry 4708 (class 2606 OID 16416)
-- Name: subscriptions subscription_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscription_records_pkey PRIMARY KEY (id);


--
-- TOC entry 4710 (class 2606 OID 16589)
-- Name: users users_email_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_unique UNIQUE (email);


--
-- TOC entry 4712 (class 2606 OID 16423)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4722 (class 2606 OID 16587)
-- Name: vnpay_transaction_logs vnpay_transaction_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vnpay_transaction_logs
    ADD CONSTRAINT vnpay_transaction_logs_pkey PRIMARY KEY (id);


--
-- TOC entry 4730 (class 2606 OID 16553)
-- Name: containers container_users_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.containers
    ADD CONSTRAINT container_users_fk FOREIGN KEY (owner_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4737 (class 2606 OID 16611)
-- Name: course_data course_data_course_folder_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_data
    ADD CONSTRAINT course_data_course_folder_fk FOREIGN KEY (folder_id) REFERENCES public.folders(id);


--
-- TOC entry 4738 (class 2606 OID 16621)
-- Name: course_data course_data_courses_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_data
    ADD CONSTRAINT course_data_courses_fk FOREIGN KEY (course_id) REFERENCES public.courses(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4732 (class 2606 OID 16494)
-- Name: files course_file_course_folder_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.files
    ADD CONSTRAINT course_file_course_folder_fk FOREIGN KEY (folder_id) REFERENCES public.folders(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4731 (class 2606 OID 16482)
-- Name: folders course_folder_container_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.folders
    ADD CONSTRAINT course_folder_container_fk FOREIGN KEY (container_id) REFERENCES public.containers(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4733 (class 2606 OID 16534)
-- Name: course_reviews course_review_courses_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_reviews
    ADD CONSTRAINT course_review_courses_fk FOREIGN KEY (course_id) REFERENCES public.courses(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4734 (class 2606 OID 16529)
-- Name: course_reviews course_review_users_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_reviews
    ADD CONSTRAINT course_review_users_fk FOREIGN KEY (reviewer_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4726 (class 2606 OID 16616)
-- Name: courses fk41jwvqd779kdvc0rdgij4ct17; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT fk41jwvqd779kdvc0rdgij4ct17 FOREIGN KEY (creator_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4727 (class 2606 OID 16626)
-- Name: courses fk72l5dj585nq7i6xxv1vj51lyn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT fk72l5dj585nq7i6xxv1vj51lyn FOREIGN KEY (category_id) REFERENCES public.categories(id) ON UPDATE CASCADE;


--
-- TOC entry 4728 (class 2606 OID 16641)
-- Name: subscriptions fkfhysei663mq62wa646n5mv5k1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT fkfhysei663mq62wa646n5mv5k1 FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4725 (class 2606 OID 16449)
-- Name: accounts fklsevhk46j1mfa8r9bak4tr4x3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT fklsevhk46j1mfa8r9bak4tr4x3 FOREIGN KEY (id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4729 (class 2606 OID 16646)
-- Name: subscriptions fkm5q12n9cpt2e99beegi4so04t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT fkm5q12n9cpt2e99beegi4so04t FOREIGN KEY (course_id) REFERENCES public.courses(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4735 (class 2606 OID 16636)
-- Name: vnpay_transaction_logs vnpay_transaction_logs_courses_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vnpay_transaction_logs
    ADD CONSTRAINT vnpay_transaction_logs_courses_fk FOREIGN KEY (course_id) REFERENCES public.courses(id) ON UPDATE CASCADE;


--
-- TOC entry 4736 (class 2606 OID 16631)
-- Name: vnpay_transaction_logs vnpay_transaction_logs_users_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vnpay_transaction_logs
    ADD CONSTRAINT vnpay_transaction_logs_users_fk FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE;


-- Completed on 2025-04-16 11:21:04

--
-- PostgreSQL database dump complete
--

