--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.0

-- Started on 2025-05-14 23:47:24

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE "KLTN";
--
-- TOC entry 4902 (class 1262 OID 16387)
-- Name: KLTN; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "KLTN" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'English_United States.1252';


ALTER DATABASE "KLTN" OWNER TO postgres;

\connect "KLTN"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 4903 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- TOC entry 234 (class 1255 OID 16388)
-- Name: update_subscriber_number(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.update_subscriber_number() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    -- Khi có người subscribe (INSERT)
    IF TG_OP = 'INSERT' THEN
        UPDATE courses
        SET subscriber_number = subscriber_number + 1
        WHERE id = NEW.course_id;

    -- Khi có người unsubscribe (DELETE)
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE courses
        SET subscriber_number = subscriber_number - 1
        WHERE id = OLD.course_id;
    END IF;

    RETURN NULL;
END;
$$;


ALTER FUNCTION public.update_subscriber_number() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 16389)
-- Name: accounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts (
    id character varying(255) NOT NULL,
    password character varying(255),
    provider character varying(255),
    role character varying(255) DEFAULT USER
);


ALTER TABLE public.accounts OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16394)
-- Name: categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categories (
    id integer NOT NULL,
    name character varying(255),
    description character varying(255)
);


ALTER TABLE public.categories OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16399)
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16400)
-- Name: containers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.containers (
    id uuid NOT NULL,
    name character varying(255),
    created_at timestamp without time zone DEFAULT now(),
    course_id integer
);


ALTER TABLE public.containers OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16410)
-- Name: course_reviews; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.course_reviews (
    id integer NOT NULL,
    course_id integer,
    reviewer_id character varying,
    comment character varying(100),
    star_rate integer,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.course_reviews OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16416)
-- Name: course_review_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.course_reviews ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.course_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16417)
-- Name: courses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.courses (
    id integer NOT NULL,
    created_at timestamp(6) without time zone DEFAULT now(),
    creator_id character varying(255),
    description text,
    is_available boolean,
    price numeric(38,2),
    status character varying(255),
    thumbnail_url character varying(255),
    title character varying(255),
    category_id integer,
    subscriber_number bigint DEFAULT 0,
    is_featured boolean
);


ALTER TABLE public.courses OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16424)
-- Name: courses_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.courses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16425)
-- Name: files; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.files (
    id uuid NOT NULL,
    name character varying(255),
    type character varying(255),
    container_id uuid,
    created_at timestamp(6) without time zone DEFAULT now(),
    url text,
    extension character varying(255),
    author_id character varying(255),
    status character varying(255)
);


ALTER TABLE public.files OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 24579)
-- Name: messages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.messages (
);


ALTER TABLE public.messages OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16431)
-- Name: subscriptions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.subscriptions (
    id integer NOT NULL,
    bought_price numeric(38,2),
    status character varying(255),
    created_at timestamp(6) without time zone DEFAULT now() NOT NULL,
    course_id integer,
    user_id character varying(255)
);


ALTER TABLE public.subscriptions OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16437)
-- Name: subscription_records_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.subscriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscription_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 24601)
-- Name: user_favourites; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_favourites (
    id integer NOT NULL,
    created_at timestamp(6) without time zone DEFAULT now(),
    course_id integer,
    user_id character varying(255)
);


ALTER TABLE public.user_favourites OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 24600)
-- Name: user_favourites_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_favourites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_favourites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16438)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id character varying(255) NOT NULL,
    avatar_url character varying(255),
    email character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    phone character varying(255)
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16443)
-- Name: vnpay_transaction_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vnpay_transaction_logs (
    id integer NOT NULL,
    bank_code character varying(20),
    pay_date timestamp without time zone,
    created_at timestamp without time zone DEFAULT now(),
    user_id character varying,
    course_id integer,
    amount numeric(38,2),
    is_refund_type boolean,
    description character varying,
    responde_code boolean
);


ALTER TABLE public.vnpay_transaction_logs OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16449)
-- Name: vnpay_transaction_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.vnpay_transaction_logs_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.vnpay_transaction_logs_id_seq OWNER TO postgres;

--
-- TOC entry 4904 (class 0 OID 0)
-- Dependencies: 230
-- Name: vnpay_transaction_logs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.vnpay_transaction_logs_id_seq OWNED BY public.vnpay_transaction_logs.id;


--
-- TOC entry 4880 (class 0 OID 16389)
-- Dependencies: 217
-- Data for Name: accounts; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.accounts VALUES ('admin', '$2a$10$o6lICJPWxVbhFVTzJ6G1puqNtGuvmEeaJPjESma7J5MUSTm1yNpha', 'google', 'ADMIN');
INSERT INTO public.accounts VALUES ('114137537600795110560', NULL, 'google', 'USER');
INSERT INTO public.accounts VALUES ('108654843953293656512', NULL, 'google', 'USER');
INSERT INTO public.accounts VALUES ('112941946199308652251', NULL, 'google', 'USER');
INSERT INTO public.accounts VALUES ('109667179457233586927', NULL, 'google', 'USER');
INSERT INTO public.accounts VALUES ('admin1', '$2a$10$o6lICJPWxVbhFVTzJ6G1puqNtGuvmEeaJPjESma7J5MUSTm1yNpha', 'google', 'ADMIN');
INSERT INTO public.accounts VALUES ('admin2', '$2a$10$bY5jdA5QjZ75nO/Pegr4G.ztZWhbMPtKnFZOTiAMfC3e1Sx/S48ze', 'default', 'USER');


--
-- TOC entry 4881 (class 0 OID 16394)
-- Dependencies: 218
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.categories VALUES (5, 'Tiểu học / THCS', 'Bổ trợ kiến thức cấp Tiểu học và Trung học cơ sở');
INSERT INTO public.categories VALUES (6, 'Ngoại ngữ', 'Các khóa học tiếng Anh, Nhật, Hàn, TOEIC, IELTS,...');
INSERT INTO public.categories VALUES (7, 'Đời sống', 'Kiến thức đời sống như nuôi dạy con, tài chính cá nhân');
INSERT INTO public.categories VALUES (8, 'Kỹ năng mềm', 'Kỹ năng giao tiếp, làm việc nhóm, tư duy phản biện');
INSERT INTO public.categories VALUES (9, 'Tâm lý - Phát triển bản thân', 'EQ, kiểm soát cảm xúc, phát triển cá nhân');
INSERT INTO public.categories VALUES (10, 'Công nghệ thông tin', 'Tin học văn phòng, lập trình cơ bản');
INSERT INTO public.categories VALUES (11, 'Luyện thi chứng chỉ', 'MOS, IELTS, TOEIC, JLPT, các chứng chỉ chuyên môn');
INSERT INTO public.categories VALUES (12, 'Nghề nghiệp & Khởi nghiệp', 'Hướng nghiệp, viết CV, kỹ năng khởi nghiệp');
INSERT INTO public.categories VALUES (13, 'Kinh doanh & Marketing', 'Marketing online, bán hàng, quảng cáo');
INSERT INTO public.categories VALUES (14, 'Thiết kế & Sáng tạo', 'Thiết kế đồ họa, UI/UX, sáng tạo nội dung');
INSERT INTO public.categories VALUES (15, 'Pháp luật & Xã hội', 'Hiểu biết về luật pháp, xã hội và công dân');
INSERT INTO public.categories VALUES (16, 'Sức khỏe & Thể chất', 'Dinh dưỡng, yoga, thiền, rèn luyện thể chất');
INSERT INTO public.categories VALUES (1, 'Giáo dục', 'Kiến thức học thuật và kỹ năng học tập');
INSERT INTO public.categories VALUES (2, 'THPT', 'Ôn tập chương trình Trung học phổ thông');


--
-- TOC entry 4883 (class 0 OID 16400)
-- Dependencies: 220
-- Data for Name: containers; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.containers VALUES ('fa448942-18b9-451f-b15b-59a82fe5b633', 'gdgdfgdfg', '2025-05-11 00:25:08.968', 1);
INSERT INTO public.containers VALUES ('fa448942-18b9-451f-b15b-59a82fe5b639', 'gdgdfgdfg', '2025-05-11 00:25:08.968', 1);
INSERT INTO public.containers VALUES ('c5b3157b-81fd-4de2-a5a5-3f544bd71fa0', 'Thư mục 1 - chứa các file test', '2025-05-11 20:49:54.131', 58);


--
-- TOC entry 4884 (class 0 OID 16410)
-- Dependencies: 221
-- Data for Name: course_reviews; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (1, 1, 'admin', 'dở ói', 3, '2025-04-17 16:15:52.735443');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (3, 1, 'admin', 'Dở tệ', 1, '2025-04-17 16:16:09.274625');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (4, 1, 'admin', 'Hay mà', 5, '2025-04-17 16:16:09.274625');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (5, 1, 'admin', 'Dở tệ', 1, '2025-04-17 20:28:01.344718');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (7, 1, 'admin', 'Dở ẹc á', 1, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (8, 2, '114137537600795110560', 'Ngon nghẻ!', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (9, 1, '108654843953293656512', 'Bình thường như cân đường hộp sữa', 3, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (12, 1, 'admin', 'Gà thật sự', 1, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (13, 2, '108654843953293656512', 'Hơi bị đỉnh', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (14, 1, 'admin', 'Thường thôi', 3, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (15, 1, '114137537600795110560', 'Chán òm', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (17, 1, '108654843953293656512', 'Trên cả tuyệt vời', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (19, 1, '114137537600795110560', 'Còn hơn cả mong đợi', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (20, 1, 'admin', 'Hơi chán', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (21, 2, '108654843953293656512', 'Xem cũng được', 3, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (22, 1, 'admin', 'Không đáng tiền', 1, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (23, 2, '114137537600795110560', 'Đáng đồng tiền bát gạo', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (24, 1, 'admin', 'Siêu phẩm!', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (27, 1, '114137537600795110560', 'Dở tệ', 1, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (29, 1, '108654843953293656512', 'Không cảm xúc', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (30, 1, 'admin', 'Cười xỉu', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (31, 2, '114137537600795110560', 'Xàm xí đú', 3, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (32, 1, 'admin', 'Tuyệt vời ông mặt trời', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (34, 1, 'admin', 'Thích quá trời', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (35, 1, '114137537600795110560', 'Tệ lắm luôn', 1, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (37, 1, '108654843953293656512', 'Thất vọng', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (38, 1, 'admin', 'Bất ngờ ghê', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (39, 2, '114137537600795110560', 'Kỳ vọng nhiều hơn', 3, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (40, 1, 'admin', 'Học vui', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (41, 2, '108654843953293656512', 'Không học được gì', 1, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (42, 1, 'admin', 'Nội dung chán', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (43, 2, '114137537600795110560', 'Không logic lắm', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (44, 1, 'admin', 'Giải thích dễ hiểu', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (45, 2, '108654843953293656512', 'Có tâm ghê', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (47, 2, '114137537600795110560', 'Dài dòng', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (49, 2, '108654843953293656512', 'Chuyên nghiệp', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (50, 1, 'admin', 'Rối quá', 1, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (51, 2, '114137537600795110560', 'Hướng dẫn dễ hiểu', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (52, 1, 'admin', 'Tài liệu xịn', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (54, 1, 'admin', 'Sẽ giới thiệu bạn bè', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (55, 2, '114137537600795110560', 'Tạm ổn', 3, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (56, 1, 'admin', 'Còn thiếu', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (57, 2, '108654843953293656512', 'Xịn xò', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (58, 1, 'admin', 'Chất lượng cao', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (60, 1, 'admin', 'Lung linh', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (61, 2, '108654843953293656512', 'Ngon bá cháy', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (62, 1, 'admin', 'Không hiểu gì luôn', 1, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (63, 2, '114137537600795110560', 'Rất đáng học', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (64, 1, 'admin', 'Tưởng hay ai ngờ dở', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (65, 2, '108654843953293656512', 'Quá đỉnh', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (66, 1, 'admin', 'Quá chán', 1, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (67, 2, '114137537600795110560', 'Nội dung chất lượng', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (68, 1, 'admin', 'Không cảm thấy hữu ích', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (69, 2, '108654843953293656512', 'Quá hay luôn', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (70, 1, 'admin', 'Còn thiếu ví dụ', 3, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (72, 1, 'admin', 'Cần thêm bài tập', 3, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (73, 2, '108654843953293656512', 'Thầy dạy vui', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (75, 2, '114137537600795110560', 'Giọng hay ghê', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (76, 1, 'admin', 'Phụ đề lỗi', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (77, 2, '108654843953293656512', 'Chỉnh chu', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (78, 1, 'admin', 'Chưa cập nhật nội dung mới', 3, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (79, 2, '114137537600795110560', 'Giá quá rẻ cho chất lượng', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (80, 1, 'admin', 'Khó tiếp cận', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (81, 2, '108654843953293656512', 'Thực tế và gần gũi', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (82, 1, 'admin', 'Slide trình bày rối', 3, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (83, 2, '114137537600795110560', 'Tương tác tốt', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (84, 1, 'admin', 'Không có phần bài tập', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (85, 2, '108654843953293656512', 'Ví dụ minh hoạ dễ hiểu', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (86, 1, 'admin', 'Thấy hơi lan man', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (87, 2, '114137537600795110560', 'Quá xịn luôn!', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (88, 1, 'admin', 'Hơi dài dòng', 3, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (89, 2, '108654843953293656512', 'Cách tiếp cận mới mẻ', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (90, 1, 'admin', 'Không chuyên sâu lắm', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (91, 2, '114137537600795110560', 'Tổng quan rất ổn', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (92, 1, 'admin', 'Cần cải thiện phần thực hành', 3, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (93, 2, '108654843953293656512', 'Học là ghiền', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (94, 1, 'admin', 'Chưa đủ thuyết phục', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (95, 2, '114137537600795110560', 'Thầy giảng có tâm', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (96, 1, 'admin', 'Thiếu phần ôn tập', 3, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (97, 2, '108654843953293656512', 'Làm rất có tâm', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (98, 1, 'admin', 'Không theo kịp', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (99, 2, '114137537600795110560', 'Khóa học đáng giá', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (100, 1, 'admin', 'Không rõ phần cuối', 3, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (101, 2, '108654843953293656512', 'Tổng hợp tốt', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (102, 1, 'admin', 'Không mạch lạc', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (103, 2, '114137537600795110560', 'Cấu trúc hợp lý', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (104, 1, 'admin', 'Chưa hấp dẫn lắm', 3, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (105, 2, '108654843953293656512', 'Học xong lên trình liền', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (106, 1, 'admin', 'Cần nhiều ví dụ hơn', 3, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (107, 2, '114137537600795110560', 'Giao diện dễ nhìn', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (108, 1, 'admin', 'Cần thêm phụ đề', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (109, 2, '108654843953293656512', 'Xứng đáng điểm 10', 5, '2025-04-17 21:54:31.726025');


--
-- TOC entry 4886 (class 0 OID 16417)
-- Dependencies: 223
-- Data for Name: courses; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.courses VALUES (2, '2025-04-17 10:21:02.735784', 'admin', '<div> <p><strong>🎯 Khóa học: Chinh phục Đánh giá năng lực – Bao 800+</strong></p> <p>✅ <strong>Mục tiêu:</strong> Giúp bạn đạt điểm trên <strong>800+</strong> trong kỳ thi Đánh giá năng lực. Nội dung được thiết kế dễ hiểu, bám sát đề thi thực tế, phù hợp với mọi trình độ học sinh từ cơ bản đến nâng cao.</p> <p>📚 <strong>Nội dung khóa học:</strong></p> <ul> <li>🧠 Tổng ôn Tư duy định lượng, định tính, và kỹ năng ngôn ngữ</li> <li>✍️ Bài giảng chi tiết, dễ hiểu, bám sát cấu trúc đề thi thật</li> <li>📝 Bộ đề luyện tập đa dạng, có lời giải và phân tích cụ thể</li> <li>📈 Chiến lược làm bài thông minh, mẹo xử lý nhanh và chính xác</li> </ul> <p>🔥 <strong>Điểm nổi bật:</strong></p> <ul> <li>🔓 Truy cập học liệu không giới hạn – học bất cứ lúc nào</li> <li>💬 Hỗ trợ giải đáp trực tiếp từ giảng viên</li> <li>🎥 Video HD, trình bày sinh động, minh họa dễ hiểu</li> <li>💯 Cam kết chất lượng – Bao dễ hiểu, bao điểm cao</li> </ul> <p>💸 <strong>Học phí:</strong> Chỉ <strong>500.000 VNĐ</strong> – trọn gói toàn bộ nội dung, không phụ phí</p> <p>🚀 <strong>Dành cho:</strong> Học sinh lớp 11, 12 đang ôn luyện kỳ thi ĐGNL của ĐHQG TP.HCM, Hà Nội và các trường khác có tổ chức thi riêng</p> <p>📌 <strong>Cam kết:</strong> Không học lan man – chỉ tập trung kiến thức trọng tâm, có hệ thống và hiệu quả.</p> </div>', true, 120000.00, NULL, 'https://img.freepik.com/premium-vector/colorful-abstract-banner-template-with-dummy-text-web-design-landing-page-print-material_5883-2930.jpg	', 'Quản lý thời gian hiệu quả', 2, 0, true);
INSERT INTO public.courses VALUES (1, '2025-04-17 10:18:50.326729', 'admin', '<body id="tinymce" class="mce-content-body " data-id="tiny-react_45577982011746105294493" aria-label="Rich Text Area" contenteditable="true" spellcheck="false"><h1 style="text-align: center;" data-mce-style="text-align: center;"><span style="color: rgb(224, 62, 45);" data-mce-style="color: #e03e2d;">💻 🔥 Chinh Phục 9+ THPTQG Sinh Học 🔥 💻</span></h1><p>🎯 Ước mơ du học Y Dược đang chờ bạn? 🎯 Bạn băn khoăn về điểm chuẩn cao, không biết phải học như thế nào để đạt điểm số mơ ước? Đừng lo, khóa học "Chinh Phục 9+ THPTQG Sinh Học" chính là giải pháp tối ưu cho bạn! 💪</p><p>✅ Khóa học được thiết kế</p><ul><li>Với phương pháp giảng dạy khoa học, minh họa rõ ràng, dễ hiểu từ cơ bản đến nâng cao.</li><li>Mục tiêu giúp bạn đạt <strong>9 điểm trở lên thi THPTQG môn Sinh học.</strong></li><li>Tăng khả năng vận dụng kiến thức vào làm bài thi, chinh phục các dạng bài khó.</li></ul><p>✅ Với mức học phí chỉ 300k 💸, bạn đã có thể nắm trong tay khóa học chất lượng, giúp bạn</p><ul><li>Nâng cao kiến thức và kỹ năng thi môn Sinh học.</li><li>Rút ngắn thời gian ôn tập, tăng khả năng trúng nguyện Y Dược.</li><li>Tiết kiệm chi phí so với các khóa học khác.</li></ul><p>📚 Khóa học gồm:</p><ul><li>Các chương trình video học trực tuyến chất lượng cao.</li><li>Tài liệu học đầy đủ, dễ nắm bắt.</li><li>Bộ đề thi minh họa, đáp án chi tiết.</li><li>Hỗ trợ tư vấn 24/7 từ đội ngũ thầy cô giàu kinh nghiệm.</li></ul><p>💡 Hãy đăng ký ngay khóa học "Chinh Phục 9+ THPTQG Sinh Học" để:</p><ul><li>Tiến gần hơn đến ước mơ du học Y Dược.</li><li>Bắt đầu hành trình chinh phục 9 điểm Sinh học!</li></ul><p>🤷‍♂️ Thi THPT Quốc gia môn Sinh học thường bao gồm các nội dung sau:</p><ol><li>Kiến thức cơ bản về Sinh học lớp 12, bao gồm:</li></ol><ul><li>Di truyền học</li><li>Tiến hóa</li><li>Sinh thái học</li><li>Cơ thể sinh vật (cấu trúc và chức năng)</li></ul><ol start="2"><li>Các chủ đề trọng tâm:</li></ol><ul><li>Di truyền phân tử và di truyền tế bào</li><li>Cơ chế di truyền và biến dị</li><li>Ứng dụng di truyền học</li><li>Tiến hóa và đa dạng sinh học</li><li>Sinh thái và sinh quyển</li></ul><p>Môn thi Sinh học đánh giá khả năng hiểu và vận dụng kiến thức Sinh học của thí sinh. Câu hỏi có thể ở dạng lý thuyết hoặc bài tập thực hành.</p></body>', true, 150000.00, NULL, 'https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=1200&auto=format&fit=crop', 'Kỹ năng bán hàng đỉnh cao', 1, 1, true);
INSERT INTO public.courses VALUES (58, '2025-05-11 20:49:45.840319', 'admin', '<p>sdfsdf</p>', true, 0.00, NULL, 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1200&auto=format&fit=crop', 'Toán lớp 12 ôn thi THPT', 12, 1, true);


--
-- TOC entry 4888 (class 0 OID 16425)
-- Dependencies: 225
-- Data for Name: files; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.files VALUES ('ae95f65e-4d77-44e7-a615-7c6a962e2e22', 'fhfghfgh', 'iframe', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0', '2025-05-11 20:52:08.07', '<iframe width="560" height="315" src="https://www.youtube.com/embed/b_fbHSSp4Zk?si=DtNySdqo88srVYYJ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>', 'html', 'admin', NULL);
INSERT INTO public.files VALUES ('0c6ccd96-c01e-4b7c-a18e-85df8b62e9e8', 'mov', 'media-video', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0', '2025-05-11 22:05:03.636', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0/0c6ccd96-c01e-4b7c-a18e-85df8b62e9e8/0c6ccd96-c01e-4b7c-a18e-85df8b62e9e8.mov', 'mov', 'admin', NULL);
INSERT INTO public.files VALUES ('ab99ff32-24aa-4fb5-9a1a-6ffcf2b87579', 'fdgfdg', 'document', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0', '2025-05-11 22:13:45.58', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0/ab99ff32-24aa-4fb5-9a1a-6ffcf2b87579/ab99ff32-24aa-4fb5-9a1a-6ffcf2b87579.doc', 'doc', 'admin', NULL);
INSERT INTO public.files VALUES ('52855198-1aa1-4a86-9d4f-ff96f30ab554', 'golf-1', 'scorm', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0', '2025-05-11 22:14:21.516', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0/52855198-1aa1-4a86-9d4f-ff96f30ab554/unzipped/shared/launchpage.html', 'html', 'admin', NULL);
INSERT INTO public.files VALUES ('7b4c3499-8a4e-43fa-8ade-b5d779e1dda5', 'gdf', 'media-image', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0', '2025-05-11 20:50:01.134', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0/7b4c3499-8a4e-43fa-8ade-b5d779e1dda5/7b4c3499-8a4e-43fa-8ade-b5d779e1dda5.png', 'png', 'admin', NULL);
INSERT INTO public.files VALUES ('74041759-dcbe-40b8-a90f-bece0a173ca3', 'sdgfdfdg', 'media-hls', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0', '2025-05-11 20:50:11.551', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0/74041759-dcbe-40b8-a90f-bece0a173ca3/hls/index.m3u8', 'm3u8', 'admin', NULL);
INSERT INTO public.files VALUES ('2c5503ee-0781-48d5-b27c-ddb99fb75514', 'sdfgsdfg', 'media-audio', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0', '2025-05-11 20:50:54.948', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0/2c5503ee-0781-48d5-b27c-ddb99fb75514/2c5503ee-0781-48d5-b27c-ddb99fb75514.mp3', 'mp3', 'admin', NULL);
INSERT INTO public.files VALUES ('86ead9f5-3564-4d4b-af9f-31c836cf7416', 'gjghj', 'scorm', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0', '2025-05-11 20:51:11.295', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0/86ead9f5-3564-4d4b-af9f-31c836cf7416/unzipped/res/index.html', 'html', 'admin', NULL);
INSERT INTO public.files VALUES ('4b0fece0-ee59-4ea7-b257-7cdb80e7b878', 'jghjgh', 'document', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0', '2025-05-11 20:51:18.955', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0/4b0fece0-ee59-4ea7-b257-7cdb80e7b878/4b0fece0-ee59-4ea7-b257-7cdb80e7b878.pptx', 'pptx', 'admin', NULL);
INSERT INTO public.files VALUES ('c61f644e-20a0-45c1-bafa-643f86762ffb', 'fdhdfgh', 'document', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0', '2025-05-11 20:51:55.984', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0/c61f644e-20a0-45c1-bafa-643f86762ffb/c61f644e-20a0-45c1-bafa-643f86762ffb.docx', 'docx', 'admin', NULL);
INSERT INTO public.files VALUES ('aa31672f-4747-4702-b2cc-1a5e6e48ac9b', 'k;kl;k', 'document', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0', '2025-05-11 21:06:34.996', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0/aa31672f-4747-4702-b2cc-1a5e6e48ac9b/aa31672f-4747-4702-b2cc-1a5e6e48ac9b.pdf', 'pdf', 'admin', NULL);
INSERT INTO public.files VALUES ('2468b1be-21e3-4233-8a74-6f12306bdc8a', 'ghfhgfgh', 'link', 'c5b3157b-81fd-4de2-a5a5-3f544bd71fa0', '2025-05-11 20:52:04.614', 'https://www.google.com', 'url', 'admin', NULL);


--
-- TOC entry 4894 (class 0 OID 24579)
-- Dependencies: 231
-- Data for Name: messages; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4889 (class 0 OID 16431)
-- Dependencies: 226
-- Data for Name: subscriptions; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.subscriptions VALUES (9, 150000.00, NULL, '2025-05-12 21:17:09.297567', 1, 'admin2');
INSERT INTO public.subscriptions VALUES (10, 0.00, NULL, '2025-05-13 03:52:19.564254', 58, 'admin');


--
-- TOC entry 4896 (class 0 OID 24601)
-- Dependencies: 233
-- Data for Name: user_favourites; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.user_favourites VALUES (15, '2025-05-14 23:45:46.189852', 2, 'admin');


--
-- TOC entry 4891 (class 0 OID 16438)
-- Dependencies: 228
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.users VALUES ('admin', 'https://lh3.googleusercontent.com/a/ACg8ocLzGeafaRFo6EX1ckIUjB5DjW9FEI3wx2ol7_s2kWAFFnftgXCy=s96-c', 'ducle140503@gmail.com', 'Đức', 'Minh', '0123456789');
INSERT INTO public.users VALUES ('114137537600795110560', 'https://lh3.googleusercontent.com/a/ACg8ocJYx_PH3wJOhMWqmDR5KUgU8cEnBh1Ma7ULegvbzqXNZpswttg=s96-c', 'ducle14050301@gmail.com', 'Duc', 'Minh', NULL);
INSERT INTO public.users VALUES ('108654843953293656512', 'https://lh3.googleusercontent.com/a/ACg8ocJn5FRQndMyomOG_DEoFuPXEk1Pi-Rh6FXwlQPCwO8FPky8Vw=s96-c', 'leduc14503@gmail.com', 'Đức', 'Lê', NULL);
INSERT INTO public.users VALUES ('112941946199308652251', 'https://lh3.googleusercontent.com/a/ACg8ocKthVQBkfMjDRYp3rJFa7N58Yp_LMXBexOjPJcDGuB1F5JAgK4=s96-c', '21t1080009@husc.edu.vn', 'Đức', 'Lê Minh', NULL);
INSERT INTO public.users VALUES ('109667179457233586927', 'https://lh3.googleusercontent.com/a/ACg8ocJtFB5AY6CmeFCWytzu97Q8Q3Q9drmcgPZTV2Zl_VQzLky1Uw=s96-c', 'giaovien.teacher123@gmail.com', '123', '123', NULL);
INSERT INTO public.users VALUES ('admin1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.users VALUES ('admin2', NULL, 'admin@email.com', 'Duc', 'Minh', '0382868145');


--
-- TOC entry 4892 (class 0 OID 16443)
-- Dependencies: 229
-- Data for Name: vnpay_transaction_logs; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4905 (class 0 OID 0)
-- Dependencies: 219
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categories_id_seq', 16, true);


--
-- TOC entry 4906 (class 0 OID 0)
-- Dependencies: 222
-- Name: course_review_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.course_review_id_seq', 166, true);


--
-- TOC entry 4907 (class 0 OID 0)
-- Dependencies: 224
-- Name: courses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.courses_id_seq', 71, true);


--
-- TOC entry 4908 (class 0 OID 0)
-- Dependencies: 227
-- Name: subscription_records_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.subscription_records_id_seq', 12, true);


--
-- TOC entry 4909 (class 0 OID 0)
-- Dependencies: 232
-- Name: user_favourites_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_favourites_id_seq', 15, true);


--
-- TOC entry 4910 (class 0 OID 0)
-- Dependencies: 230
-- Name: vnpay_transaction_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.vnpay_transaction_logs_id_seq', 1, false);


--
-- TOC entry 4697 (class 2606 OID 16451)
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);


--
-- TOC entry 4699 (class 2606 OID 16453)
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- TOC entry 4707 (class 2606 OID 16457)
-- Name: files course_file_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.files
    ADD CONSTRAINT course_file_pk PRIMARY KEY (id);


--
-- TOC entry 4701 (class 2606 OID 16459)
-- Name: containers course_folder_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.containers
    ADD CONSTRAINT course_folder_pk PRIMARY KEY (id);


--
-- TOC entry 4703 (class 2606 OID 16461)
-- Name: course_reviews course_review_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_reviews
    ADD CONSTRAINT course_review_pk PRIMARY KEY (id);


--
-- TOC entry 4705 (class 2606 OID 16463)
-- Name: courses courses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT courses_pkey PRIMARY KEY (id);


--
-- TOC entry 4709 (class 2606 OID 16465)
-- Name: subscriptions subscription_records_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscription_records_pkey PRIMARY KEY (id);


--
-- TOC entry 4711 (class 2606 OID 24630)
-- Name: subscriptions subscriptions_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscriptions_unique UNIQUE (course_id, user_id);


--
-- TOC entry 4719 (class 2606 OID 24605)
-- Name: user_favourites user_favourites_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_favourites
    ADD CONSTRAINT user_favourites_pkey PRIMARY KEY (id);


--
-- TOC entry 4713 (class 2606 OID 16467)
-- Name: users users_email_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_unique UNIQUE (email);


--
-- TOC entry 4715 (class 2606 OID 16469)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4717 (class 2606 OID 16471)
-- Name: vnpay_transaction_logs vnpay_transaction_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vnpay_transaction_logs
    ADD CONSTRAINT vnpay_transaction_logs_pkey PRIMARY KEY (id);


--
-- TOC entry 4734 (class 2620 OID 16472)
-- Name: subscriptions trg_update_subscriber_number; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_update_subscriber_number AFTER INSERT OR DELETE ON public.subscriptions FOR EACH ROW EXECUTE FUNCTION public.update_subscriber_number();


--
-- TOC entry 4726 (class 2606 OID 16483)
-- Name: files course_file_course_folder_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.files
    ADD CONSTRAINT course_file_course_folder_fk FOREIGN KEY (container_id) REFERENCES public.containers(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4722 (class 2606 OID 16488)
-- Name: course_reviews course_review_courses_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_reviews
    ADD CONSTRAINT course_review_courses_fk FOREIGN KEY (course_id) REFERENCES public.courses(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4723 (class 2606 OID 24636)
-- Name: course_reviews course_review_users_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_reviews
    ADD CONSTRAINT course_review_users_fk FOREIGN KEY (reviewer_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4724 (class 2606 OID 16503)
-- Name: courses fk41jwvqd779kdvc0rdgij4ct17; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT fk41jwvqd779kdvc0rdgij4ct17 FOREIGN KEY (creator_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4725 (class 2606 OID 16508)
-- Name: courses fk72l5dj585nq7i6xxv1vj51lyn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT fk72l5dj585nq7i6xxv1vj51lyn FOREIGN KEY (category_id) REFERENCES public.categories(id) ON UPDATE CASCADE;


--
-- TOC entry 4732 (class 2606 OID 24617)
-- Name: user_favourites fkf4mgriav7n8cijq18001fsy6e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_favourites
    ADD CONSTRAINT fkf4mgriav7n8cijq18001fsy6e FOREIGN KEY (course_id) REFERENCES public.courses(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4728 (class 2606 OID 16513)
-- Name: subscriptions fkfhysei663mq62wa646n5mv5k1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT fkfhysei663mq62wa646n5mv5k1 FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4727 (class 2606 OID 24592)
-- Name: files fkj1y8cv1ty40nltgt267oqwmk8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.files
    ADD CONSTRAINT fkj1y8cv1ty40nltgt267oqwmk8 FOREIGN KEY (author_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4720 (class 2606 OID 16518)
-- Name: accounts fklsevhk46j1mfa8r9bak4tr4x3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT fklsevhk46j1mfa8r9bak4tr4x3 FOREIGN KEY (id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4729 (class 2606 OID 16523)
-- Name: subscriptions fkm5q12n9cpt2e99beegi4so04t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT fkm5q12n9cpt2e99beegi4so04t FOREIGN KEY (course_id) REFERENCES public.courses(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4733 (class 2606 OID 24622)
-- Name: user_favourites fksotykjapinh9k0qddenalw94k; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_favourites
    ADD CONSTRAINT fksotykjapinh9k0qddenalw94k FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4721 (class 2606 OID 24587)
-- Name: containers fkt2s02o8n8cpl64ctd5q5fkyp3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.containers
    ADD CONSTRAINT fkt2s02o8n8cpl64ctd5q5fkyp3 FOREIGN KEY (course_id) REFERENCES public.courses(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4730 (class 2606 OID 16533)
-- Name: vnpay_transaction_logs vnpay_transaction_logs_courses_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vnpay_transaction_logs
    ADD CONSTRAINT vnpay_transaction_logs_courses_fk FOREIGN KEY (course_id) REFERENCES public.courses(id) ON UPDATE CASCADE;


--
-- TOC entry 4731 (class 2606 OID 16538)
-- Name: vnpay_transaction_logs vnpay_transaction_logs_users_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vnpay_transaction_logs
    ADD CONSTRAINT vnpay_transaction_logs_users_fk FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE;


-- Completed on 2025-05-14 23:47:25

--
-- PostgreSQL database dump complete
--

