--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.0

-- Started on 2025-04-20 02:31:48

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4900 (class 1262 OID 16387)
-- Name: KLTN; Type: DATABASE; Schema: -; Owner: -
--

CREATE DATABASE "KLTN" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Vietnamese_Vietnam.1258';


\connect "KLTN"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- TOC entry 4901 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- TOC entry 238 (class 1255 OID 16721)
-- Name: update_subscriber_number(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.update_subscriber_number() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    -- Khi có người subscribe (INSERT)
    IF TG_OP = 'INSERT' THEN
        UPDATE courses
        SET subscriber_number = subscriber_number + 1
        WHERE id = NEW.course_id;

    -- Khi có người unsubscribe (DELETE)
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE courses
        SET subscriber_number = subscriber_number - 1
        WHERE id = OLD.course_id;
    END IF;

    RETURN NULL;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16388)
-- Name: accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts (
    id character varying(255) NOT NULL,
    password character varying(255),
    provider character varying(255),
    role character varying(255)
);


--
-- TOC entry 220 (class 1259 OID 16396)
-- Name: categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categories (
    id integer NOT NULL,
    name character varying(255),
    description character varying(255)
);


--
-- TOC entry 219 (class 1259 OID 16395)
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16475)
-- Name: containers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.containers (
    id uuid NOT NULL,
    name character varying(255),
    created_at timestamp without time zone DEFAULT now(),
    owner_id character varying(255),
    container_id integer
);


--
-- TOC entry 233 (class 1259 OID 16606)
-- Name: course_data; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_data (
    id integer NOT NULL,
    container_id uuid,
    course_id integer
);


--
-- TOC entry 232 (class 1259 OID 16605)
-- Name: course_data_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.course_data ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.course_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16522)
-- Name: course_reviews; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_reviews (
    id integer NOT NULL,
    course_id integer,
    reviewer_id character varying(255),
    comment text,
    star_rate integer,
    created_at timestamp without time zone DEFAULT now()
);


--
-- TOC entry 228 (class 1259 OID 16521)
-- Name: course_review_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.course_reviews ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.course_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16402)
-- Name: courses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.courses (
    id integer NOT NULL,
    created_at timestamp(6) without time zone DEFAULT now(),
    creator_id character varying(255),
    description text,
    is_available boolean,
    price numeric(38,2),
    status character varying(255),
    thumbnail_url character varying(255),
    title character varying(255),
    category_id integer,
    subscriber_number bigint DEFAULT 0
);


--
-- TOC entry 221 (class 1259 OID 16401)
-- Name: courses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.courses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16487)
-- Name: files; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.files (
    id uuid NOT NULL,
    name character varying(255),
    type character varying(10),
    container_id uuid,
    created_at timestamp(6) without time zone DEFAULT now(),
    url text,
    extension character varying(255)
);


--
-- TOC entry 224 (class 1259 OID 16410)
-- Name: subscriptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subscriptions (
    id integer NOT NULL,
    bought_price numeric(38,2),
    status character varying(255),
    created_at timestamp(6) without time zone DEFAULT now(),
    course_id integer,
    user_id character varying(255)
);


--
-- TOC entry 223 (class 1259 OID 16409)
-- Name: subscription_records_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.subscriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscription_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16417)
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id character varying(255) NOT NULL,
    avatar_url character varying(255),
    email character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    phone character varying(255)
);


--
-- TOC entry 231 (class 1259 OID 16571)
-- Name: vnpay_transaction_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vnpay_transaction_logs (
    id integer NOT NULL,
    bank_code character varying(20),
    pay_date timestamp without time zone,
    created_at timestamp without time zone DEFAULT now(),
    user_id character varying,
    course_id integer,
    amount numeric(38,2),
    is_refund_type boolean,
    description character varying,
    responde_code boolean
);


--
-- TOC entry 230 (class 1259 OID 16570)
-- Name: vnpay_transaction_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.vnpay_transaction_logs_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 4902 (class 0 OID 0)
-- Dependencies: 230
-- Name: vnpay_transaction_logs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.vnpay_transaction_logs_id_seq OWNED BY public.vnpay_transaction_logs.id;


--
-- TOC entry 4879 (class 0 OID 16388)
-- Dependencies: 218
-- Data for Name: accounts; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.accounts VALUES ('admin', '$2a$10$o6lICJPWxVbhFVTzJ6G1puqNtGuvmEeaJPjESma7J5MUSTm1yNpha', 'google', 'ADMIN');
INSERT INTO public.accounts VALUES ('114137537600795110560', NULL, 'google', 'USER');
INSERT INTO public.accounts VALUES ('108654843953293656512', NULL, 'google', 'USER');
INSERT INTO public.accounts VALUES ('112941946199308652251', NULL, 'google', 'USER');


--
-- TOC entry 4881 (class 0 OID 16396)
-- Dependencies: 220
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.categories VALUES (1, 'Loại 1', NULL);
INSERT INTO public.categories VALUES (2, 'Loại 2', NULL);


--
-- TOC entry 4887 (class 0 OID 16475)
-- Dependencies: 226
-- Data for Name: containers; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.containers VALUES ('d783ad0a-09ac-4505-a343-8cf776350d2d', 'Bài giảng SCORM', '2025-04-19 09:50:48.562177', 'admin', NULL);
INSERT INTO public.containers VALUES ('87ba9bac-7977-494d-8549-9b5e20b67cd8', 'Video bài giảng', '2025-04-19 09:51:13.140464', 'admin', NULL);


--
-- TOC entry 4894 (class 0 OID 16606)
-- Dependencies: 233
-- Data for Name: course_data; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.course_data OVERRIDING SYSTEM VALUE VALUES (1, 'd783ad0a-09ac-4505-a343-8cf776350d2d', 1);
INSERT INTO public.course_data OVERRIDING SYSTEM VALUE VALUES (2, '87ba9bac-7977-494d-8549-9b5e20b67cd8', 1);


--
-- TOC entry 4890 (class 0 OID 16522)
-- Dependencies: 229
-- Data for Name: course_reviews; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (1, 1, 'admin', 'dở ói', 3, '2025-04-17 16:15:52.735443');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (2, 1, 'admin', 'Không tệ', 4, '2025-04-17 16:16:09.274625');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (3, 1, 'admin', 'Dở tệ', 1, '2025-04-17 16:16:09.274625');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (4, 1, 'admin', 'Hay mà', 5, '2025-04-17 16:16:09.274625');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (5, 1, 'admin', 'Dở tệ', 1, '2025-04-17 20:28:01.344718');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (6, 2, 'admin', 'Hayyyyyyyyyyyyy ó', 5, '2025-04-17 21:45:57.086202');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (7, 1, 'admin', 'Dở ẹc á', 1, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (8, 2, '114137537600795110560', 'Ngon nghẻ!', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (9, 1, '108654843953293656512', 'Bình thường như cân đường hộp sữa', 3, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (10, 2, 'admin', 'Tạm được', 4, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (11, 1, '114137537600795110560', 'Cũng ổn áp', 4, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (12, 1, 'admin', 'Gà thật sự', 1, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (13, 2, '108654843953293656512', 'Hơi bị đỉnh', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (14, 1, 'admin', 'Thường thôi', 3, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (15, 1, '114137537600795110560', 'Chán òm', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (16, 2, 'admin', 'Hay quá trời hay luôn', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (17, 1, '108654843953293656512', 'Trên cả tuyệt vời', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (18, 2, 'admin', 'Không tệ', 4, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (19, 1, '114137537600795110560', 'Còn hơn cả mong đợi', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (20, 1, 'admin', 'Hơi chán', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (21, 2, '108654843953293656512', 'Xem cũng được', 3, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (22, 1, 'admin', 'Không đáng tiền', 1, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (23, 2, '114137537600795110560', 'Đáng đồng tiền bát gạo', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (24, 1, 'admin', 'Siêu phẩm!', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (25, 1, '108654843953293656512', 'Hài hước ghê', 4, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (26, 2, 'admin', 'Ngủ gật luôn', 1, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (27, 1, '114137537600795110560', 'Dở tệ', 1, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (28, 2, 'admin', 'Hay nha', 4, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (29, 1, '108654843953293656512', 'Không cảm xúc', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (30, 1, 'admin', 'Cười xỉu', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (31, 2, '114137537600795110560', 'Xàm xí đú', 3, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (32, 1, 'admin', 'Tuyệt vời ông mặt trời', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (33, 2, '108654843953293656512', 'Mlem mlem', 4, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (34, 1, 'admin', 'Thích quá trời', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (35, 1, '114137537600795110560', 'Tệ lắm luôn', 1, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (36, 2, 'admin', 'Ổn mà', 4, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (37, 1, '108654843953293656512', 'Thất vọng', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (38, 1, 'admin', 'Bất ngờ ghê', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (39, 2, '114137537600795110560', 'Kỳ vọng nhiều hơn', 3, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (40, 1, 'admin', 'Học vui', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (41, 2, '108654843953293656512', 'Không học được gì', 1, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (42, 1, 'admin', 'Nội dung chán', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (43, 2, '114137537600795110560', 'Không logic lắm', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (44, 1, 'admin', 'Giải thích dễ hiểu', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (45, 2, '108654843953293656512', 'Có tâm ghê', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (46, 1, 'admin', 'Bài bản', 4, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (47, 2, '114137537600795110560', 'Dài dòng', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (48, 1, 'admin', 'Cô đọng', 4, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (49, 2, '108654843953293656512', 'Chuyên nghiệp', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (50, 1, 'admin', 'Rối quá', 1, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (51, 2, '114137537600795110560', 'Hướng dẫn dễ hiểu', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (52, 1, 'admin', 'Tài liệu xịn', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (53, 2, '108654843953293656512', 'Nên học thử', 4, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (54, 1, 'admin', 'Sẽ giới thiệu bạn bè', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (55, 2, '114137537600795110560', 'Tạm ổn', 3, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (56, 1, 'admin', 'Còn thiếu', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (57, 2, '108654843953293656512', 'Xịn xò', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (58, 1, 'admin', 'Chất lượng cao', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (59, 2, '114137537600795110560', 'Review mạnh', 4, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (60, 1, 'admin', 'Lung linh', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (61, 2, '108654843953293656512', 'Ngon bá cháy', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (62, 1, 'admin', 'Không hiểu gì luôn', 1, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (63, 2, '114137537600795110560', 'Rất đáng học', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (64, 1, 'admin', 'Tưởng hay ai ngờ dở', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (65, 2, '108654843953293656512', 'Quá đỉnh', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (66, 1, 'admin', 'Quá chán', 1, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (67, 2, '114137537600795110560', 'Nội dung chất lượng', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (68, 1, 'admin', 'Không cảm thấy hữu ích', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (69, 2, '108654843953293656512', 'Quá hay luôn', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (70, 1, 'admin', 'Còn thiếu ví dụ', 3, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (71, 2, '114137537600795110560', 'Video đẹp', 4, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (72, 1, 'admin', 'Cần thêm bài tập', 3, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (73, 2, '108654843953293656512', 'Thầy dạy vui', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (74, 1, 'admin', 'Bài học dễ hiểu', 4, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (75, 2, '114137537600795110560', 'Giọng hay ghê', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (76, 1, 'admin', 'Phụ đề lỗi', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (77, 2, '108654843953293656512', 'Chỉnh chu', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (78, 1, 'admin', 'Chưa cập nhật nội dung mới', 3, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (79, 2, '114137537600795110560', 'Giá quá rẻ cho chất lượng', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (80, 1, 'admin', 'Khó tiếp cận', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (81, 2, '108654843953293656512', 'Thực tế và gần gũi', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (82, 1, 'admin', 'Slide trình bày rối', 3, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (83, 2, '114137537600795110560', 'Tương tác tốt', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (84, 1, 'admin', 'Không có phần bài tập', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (85, 2, '108654843953293656512', 'Ví dụ minh hoạ dễ hiểu', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (86, 1, 'admin', 'Thấy hơi lan man', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (87, 2, '114137537600795110560', 'Quá xịn luôn!', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (88, 1, 'admin', 'Hơi dài dòng', 3, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (89, 2, '108654843953293656512', 'Cách tiếp cận mới mẻ', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (90, 1, 'admin', 'Không chuyên sâu lắm', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (91, 2, '114137537600795110560', 'Tổng quan rất ổn', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (92, 1, 'admin', 'Cần cải thiện phần thực hành', 3, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (93, 2, '108654843953293656512', 'Học là ghiền', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (94, 1, 'admin', 'Chưa đủ thuyết phục', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (95, 2, '114137537600795110560', 'Thầy giảng có tâm', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (96, 1, 'admin', 'Thiếu phần ôn tập', 3, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (97, 2, '108654843953293656512', 'Làm rất có tâm', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (98, 1, 'admin', 'Không theo kịp', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (99, 2, '114137537600795110560', 'Khóa học đáng giá', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (100, 1, 'admin', 'Không rõ phần cuối', 3, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (101, 2, '108654843953293656512', 'Tổng hợp tốt', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (102, 1, 'admin', 'Không mạch lạc', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (103, 2, '114137537600795110560', 'Cấu trúc hợp lý', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (104, 1, 'admin', 'Chưa hấp dẫn lắm', 3, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (105, 2, '108654843953293656512', 'Học xong lên trình liền', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (106, 1, 'admin', 'Cần nhiều ví dụ hơn', 3, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (107, 2, '114137537600795110560', 'Giao diện dễ nhìn', 5, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (108, 1, 'admin', 'Cần thêm phụ đề', 2, '2025-04-17 21:54:31.726025');
INSERT INTO public.course_reviews OVERRIDING SYSTEM VALUE VALUES (109, 2, '108654843953293656512', 'Xứng đáng điểm 10', 5, '2025-04-17 21:54:31.726025');


--
-- TOC entry 4883 (class 0 OID 16402)
-- Dependencies: 222
-- Data for Name: courses; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.courses VALUES (1, '2025-04-17 10:18:50.326729', 'admin', '<h2>Chinh phục TOEIC 800+ 🔥</h2>

<p>Muốn sở hữu điểm TOEIC trên 800 để tự tin trong việc xin việc, thăng chức hay du học? ✈️</p>
<p>Khóa học online "Chinh phục TOEIC" là giải pháp hoàn hảo dành cho bạn!</p>

<h3>Tại sao nên học với chúng tôi?</h3>
<ul>
  <li>💖 100% dễ hiểu, giảng dạy theo phương pháp học cực đơn giản, phù hợp mọi đối tượng!</li>
  <li>🥇 Cam kết giúp bạn chinh phục TOEIC 800+ 🎯, đạt điểm số mơ ước!</li>
  <li>💸 Chi phí chỉ 500k 💪, tiết kiệm thời gian và chi phí đáng kể!</li>
  <li>🚀 Nâng cao khả năng tiếng Anh 🗣️, làm đẹp CV và mở rộng cơ hội nghề nghiệp!</li>
</ul>

<h3>Lộ trình học</h3>

<p>Khóa học bao gồm:</p>
<ul>
  <li><strong>Phần 1: </strong> Cấu trúc đề thi TOEIC 📄</li>
  <li><strong>Phần 2: </strong> Kiến thức ngữ pháp chuyên sâu 📖</li>
  <li><strong>Phần 3:</strong>  Phần nghe 🎧</li>
  <li><strong>Phần 4: </strong> Phần đọc 📚</li>
  <li><strong>Phần 5:</strong>  Thực hành với đề thi 📝</li>
</ul>

<p>✔️ Kết hợp giảng dạy trực tuyến & các bài tập thực hành  🔁</p>
<p>✔️ Tự học linh hoạt bất kể thời gian địa điểm  anytime, anywhere 🌎</p>
<p>✔️ Hỗ trợ tư vấn và giải đáp thắc mắc 24/7 ตลอด 24 ชั่วโมง</p>


<h3>Đăng ký ngay hôm nay để bắt đầu con đường chinh phục điểm TOEIC 800+ của bạn!</h3> 🏆


', true, 150000.00, 'ok', 'https://img.freepik.com/premium-vector/abstract-modern-blue-technology-banner-design-web-template-set-horizontal-header-web-banner-vector-abstract-graphic-design-banner-pattern-background-template_181182-14907.jpg', 'Cẩm lan sục', 1, 1);
INSERT INTO public.courses VALUES (2, '2025-04-17 10:21:02.735784', 'admin', '<div> <p><strong>🎯 Khóa học: Chinh phục Đánh giá năng lực – Bao 800+</strong></p> <p>✅ <strong>Mục tiêu:</strong> Giúp bạn đạt điểm trên <strong>800+</strong> trong kỳ thi Đánh giá năng lực. Nội dung được thiết kế dễ hiểu, bám sát đề thi thực tế, phù hợp với mọi trình độ học sinh từ cơ bản đến nâng cao.</p> <p>📚 <strong>Nội dung khóa học:</strong></p> <ul> <li>🧠 Tổng ôn Tư duy định lượng, định tính, và kỹ năng ngôn ngữ</li> <li>✍️ Bài giảng chi tiết, dễ hiểu, bám sát cấu trúc đề thi thật</li> <li>📝 Bộ đề luyện tập đa dạng, có lời giải và phân tích cụ thể</li> <li>📈 Chiến lược làm bài thông minh, mẹo xử lý nhanh và chính xác</li> </ul> <p>🔥 <strong>Điểm nổi bật:</strong></p> <ul> <li>🔓 Truy cập học liệu không giới hạn – học bất cứ lúc nào</li> <li>💬 Hỗ trợ giải đáp trực tiếp từ giảng viên</li> <li>🎥 Video HD, trình bày sinh động, minh họa dễ hiểu</li> <li>💯 Cam kết chất lượng – Bao dễ hiểu, bao điểm cao</li> </ul> <p>💸 <strong>Học phí:</strong> Chỉ <strong>500.000 VNĐ</strong> – trọn gói toàn bộ nội dung, không phụ phí</p> <p>🚀 <strong>Dành cho:</strong> Học sinh lớp 11, 12 đang ôn luyện kỳ thi ĐGNL của ĐHQG TP.HCM, Hà Nội và các trường khác có tổ chức thi riêng</p> <p>📌 <strong>Cam kết:</strong> Không học lan man – chỉ tập trung kiến thức trọng tâm, có hệ thống và hiệu quả.</p> </div>', true, 120000.00, 'sdfsd', 'https://www.wordstream.com/wp-content/uploads/2021/07/banner-ads-examples-ncino.jpg', 'dfhfghfghfghfghfgh', 2, 0);


--
-- TOC entry 4888 (class 0 OID 16487)
-- Dependencies: 227
-- Data for Name: files; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.files VALUES ('58d3ec08-3ff0-4938-854c-bb665c039d49', 'SCORM FILE', 'scorm', 'd783ad0a-09ac-4505-a343-8cf776350d2d', '2025-04-19 10:01:40.109869', '/scorm/hi/index.html', '.zip');
INSERT INTO public.files VALUES ('58d3ec08-3ff0-4938-854c-bb665c039d48', 'SCORM FILE 2', 'scorm', 'd783ad0a-09ac-4505-a343-8cf776350d2d', '2025-04-19 10:01:40.109869', '/scorm/hi/index.html', '.zip');
INSERT INTO public.files VALUES ('58d3ec08-3ff0-4938-854c-bb665c039d47', 'Video số 1', 'video', '87ba9bac-7977-494d-8549-9b5e20b67cd8', '2025-04-19 19:49:19.541812', '/hi.mp4', '.mp4');


--
-- TOC entry 4885 (class 0 OID 16410)
-- Dependencies: 224
-- Data for Name: subscriptions; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.subscriptions VALUES (2, 10000.00, NULL, '2025-04-20 00:25:45.711193', 1, '114137537600795110560');


--
-- TOC entry 4886 (class 0 OID 16417)
-- Dependencies: 225
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.users VALUES ('admin', 'https://lh3.googleusercontent.com/a/ACg8ocLzGeafaRFo6EX1ckIUjB5DjW9FEI3wx2ol7_s2kWAFFnftgXCy=s96-c', 'ducle140503@gmail.com', 'Đức', 'Minh', '0123456789');
INSERT INTO public.users VALUES ('114137537600795110560', 'https://lh3.googleusercontent.com/a/ACg8ocJYx_PH3wJOhMWqmDR5KUgU8cEnBh1Ma7ULegvbzqXNZpswttg=s96-c', 'ducle14050301@gmail.com', 'Duc', 'Minh', NULL);
INSERT INTO public.users VALUES ('108654843953293656512', 'https://lh3.googleusercontent.com/a/ACg8ocJn5FRQndMyomOG_DEoFuPXEk1Pi-Rh6FXwlQPCwO8FPky8Vw=s96-c', 'leduc14503@gmail.com', 'Đức', 'Lê', NULL);
INSERT INTO public.users VALUES ('112941946199308652251', 'https://lh3.googleusercontent.com/a/ACg8ocKthVQBkfMjDRYp3rJFa7N58Yp_LMXBexOjPJcDGuB1F5JAgK4=s96-c', '21t1080009@husc.edu.vn', 'Đức', 'Lê Minh', NULL);


--
-- TOC entry 4892 (class 0 OID 16571)
-- Dependencies: 231
-- Data for Name: vnpay_transaction_logs; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4903 (class 0 OID 0)
-- Dependencies: 219
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.categories_id_seq', 1, true);


--
-- TOC entry 4904 (class 0 OID 0)
-- Dependencies: 232
-- Name: course_data_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.course_data_id_seq', 2, true);


--
-- TOC entry 4905 (class 0 OID 0)
-- Dependencies: 228
-- Name: course_review_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.course_review_id_seq', 109, true);


--
-- TOC entry 4906 (class 0 OID 0)
-- Dependencies: 221
-- Name: courses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.courses_id_seq', 2, true);


--
-- TOC entry 4907 (class 0 OID 0)
-- Dependencies: 223
-- Name: subscription_records_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.subscription_records_id_seq', 2, true);


--
-- TOC entry 4908 (class 0 OID 0)
-- Dependencies: 230
-- Name: vnpay_transaction_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.vnpay_transaction_logs_id_seq', 1, false);


--
-- TOC entry 4698 (class 2606 OID 16394)
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);


--
-- TOC entry 4700 (class 2606 OID 16400)
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- TOC entry 4718 (class 2606 OID 16610)
-- Name: course_data course_data_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_data
    ADD CONSTRAINT course_data_pk PRIMARY KEY (id);


--
-- TOC entry 4712 (class 2606 OID 16491)
-- Name: files course_file_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.files
    ADD CONSTRAINT course_file_pk PRIMARY KEY (id);


--
-- TOC entry 4710 (class 2606 OID 16479)
-- Name: containers course_folder_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.containers
    ADD CONSTRAINT course_folder_pk PRIMARY KEY (id);


--
-- TOC entry 4714 (class 2606 OID 16528)
-- Name: course_reviews course_review_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_reviews
    ADD CONSTRAINT course_review_pk PRIMARY KEY (id);


--
-- TOC entry 4702 (class 2606 OID 16408)
-- Name: courses courses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT courses_pkey PRIMARY KEY (id);


--
-- TOC entry 4704 (class 2606 OID 16416)
-- Name: subscriptions subscription_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscription_records_pkey PRIMARY KEY (id);


--
-- TOC entry 4706 (class 2606 OID 16589)
-- Name: users users_email_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_unique UNIQUE (email);


--
-- TOC entry 4708 (class 2606 OID 16423)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4716 (class 2606 OID 16699)
-- Name: vnpay_transaction_logs vnpay_transaction_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vnpay_transaction_logs
    ADD CONSTRAINT vnpay_transaction_logs_pkey PRIMARY KEY (id);


--
-- TOC entry 4733 (class 2620 OID 16722)
-- Name: subscriptions trg_update_subscriber_number; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_update_subscriber_number AFTER INSERT OR DELETE ON public.subscriptions FOR EACH ROW EXECUTE FUNCTION public.update_subscriber_number();


--
-- TOC entry 4731 (class 2606 OID 16611)
-- Name: course_data course_data_course_folder_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_data
    ADD CONSTRAINT course_data_course_folder_fk FOREIGN KEY (container_id) REFERENCES public.containers(id);


--
-- TOC entry 4732 (class 2606 OID 16621)
-- Name: course_data course_data_courses_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_data
    ADD CONSTRAINT course_data_courses_fk FOREIGN KEY (course_id) REFERENCES public.courses(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4726 (class 2606 OID 16494)
-- Name: files course_file_course_folder_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.files
    ADD CONSTRAINT course_file_course_folder_fk FOREIGN KEY (container_id) REFERENCES public.containers(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4727 (class 2606 OID 16534)
-- Name: course_reviews course_review_courses_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_reviews
    ADD CONSTRAINT course_review_courses_fk FOREIGN KEY (course_id) REFERENCES public.courses(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4728 (class 2606 OID 16674)
-- Name: course_reviews course_review_users_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_reviews
    ADD CONSTRAINT course_review_users_fk FOREIGN KEY (reviewer_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4724 (class 2606 OID 16716)
-- Name: containers fk3p6np7avpbpj8i6uvhc8bwc4y; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.containers
    ADD CONSTRAINT fk3p6np7avpbpj8i6uvhc8bwc4y FOREIGN KEY (container_id) REFERENCES public.course_data(id);


--
-- TOC entry 4720 (class 2606 OID 16616)
-- Name: courses fk41jwvqd779kdvc0rdgij4ct17; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT fk41jwvqd779kdvc0rdgij4ct17 FOREIGN KEY (creator_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4721 (class 2606 OID 16626)
-- Name: courses fk72l5dj585nq7i6xxv1vj51lyn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT fk72l5dj585nq7i6xxv1vj51lyn FOREIGN KEY (category_id) REFERENCES public.categories(id) ON UPDATE CASCADE;


--
-- TOC entry 4722 (class 2606 OID 16641)
-- Name: subscriptions fkfhysei663mq62wa646n5mv5k1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT fkfhysei663mq62wa646n5mv5k1 FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4719 (class 2606 OID 16449)
-- Name: accounts fklsevhk46j1mfa8r9bak4tr4x3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT fklsevhk46j1mfa8r9bak4tr4x3 FOREIGN KEY (id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4723 (class 2606 OID 16646)
-- Name: subscriptions fkm5q12n9cpt2e99beegi4so04t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT fkm5q12n9cpt2e99beegi4so04t FOREIGN KEY (course_id) REFERENCES public.courses(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4725 (class 2606 OID 16710)
-- Name: containers fkn3vxhxi7lr67034fhmosgissy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.containers
    ADD CONSTRAINT fkn3vxhxi7lr67034fhmosgissy FOREIGN KEY (owner_id) REFERENCES public.users(id);


--
-- TOC entry 4729 (class 2606 OID 16636)
-- Name: vnpay_transaction_logs vnpay_transaction_logs_courses_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vnpay_transaction_logs
    ADD CONSTRAINT vnpay_transaction_logs_courses_fk FOREIGN KEY (course_id) REFERENCES public.courses(id) ON UPDATE CASCADE;


--
-- TOC entry 4730 (class 2606 OID 16631)
-- Name: vnpay_transaction_logs vnpay_transaction_logs_users_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vnpay_transaction_logs
    ADD CONSTRAINT vnpay_transaction_logs_users_fk FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE;


-- Completed on 2025-04-20 02:31:48

--
-- PostgreSQL database dump complete
--

