spring.application.name=sp1
spring.datasource.url=jdbc:postgresql://localhost:1434/KLTN
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
JWT-SECRECT-KEY:17354fc77fc11820f7861ec392607b402c1d415fbb1b8e056d3e4eca78c84d0e
