plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.4'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    compileOnly 'org.projectlombok:lombok'
//    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    runtimeOnly 'org.postgresql:postgresql'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    implementation "org.springframework.boot:spring-boot-starter-security"
    // https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-validation
    implementation 'org.springframework.boot:spring-boot-starter-validation:3.4.4'
    // https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt
    implementation 'io.jsonwebtoken:jjwt:0.12.6'
    // https://mvnrepository.com/artifact/org.springframework.security/spring-security-oauth2-client
    implementation 'org.springframework.security:spring-security-oauth2-client:6.4.4'
    // https://mvnrepository.com/artifact/commons-codec/commons-codec
    implementation 'commons-codec:commons-codec:1.18.0'
    // https://mvnrepository.com/artifact/software.amazon.awssdk/s3
    implementation 'software.amazon.awssdk:s3:2.31.20'

    // AWS SDK S3: Cung cấp S3Client và các API liên quan đến S3
    implementation 'software.amazon.awssdk:s3:2.31.20'

    // AWS SDK Apache HTTP Client: Cung cấp ApacheHttpClient để tùy chỉnh HTTP
    implementation 'software.amazon.awssdk:apache-client:2.31.20'

    // AWS SDK Core: Cung cấp các thành phần cốt lõi
    implementation 'software.amazon.awssdk:aws-core:2.31.20'

    // AWS SDK Auth: Cung cấp các cơ chế xác thực, bao gồm AwsBasicCredentials
    implementation 'software.amazon.awssdk:auth:2.31.20'
    // https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-websocket
    implementation 'org.springframework.boot:spring-boot-starter-websocket:3.4.4'
    // https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-amqp
    implementation 'org.springframework.boot:spring-boot-starter-amqp:3.4.4'
    // https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-thymeleaf
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf:3.4.4'
}

tasks.named('test') {
    useJUnitPlatform()
}
