import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ChatBox from "@/components/floating-chatbox";

// import { ThemeProvider } from "@/components/theme-provider"

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: "eEdu - E-Learning Material Provider",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi" className={`${inter.variable} antialiased`}>
      <body className="font-inter">
        {children}
       <ChatBox/>
      </body>
    </html>
  );
}
